# Generated by Django 6.1 on 2026-08-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_inventory_data'),
        ('schools', '0006_school_institution_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='schools.campus'),
        ),
    ]
