# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_campus'),
        ('schools', '0008_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_assets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='schools.school'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_asset_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_asset_category_name_per_institution'),
        ),
    ]
