# Generated by Django 6.1 on 2026-08-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_institution_to_all_models'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.CharField(blank=True, default='pcs', help_text='Tracking unit for stock, e.g. pcs, box, litre.', max_length=30),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receive', 'Received'), ('issue', 'Issued'), ('return', 'Returned'), ('transfer_in', 'Received (transfer)'), ('transfer_out', 'Issued (transfer)'), ('write_off', 'Written off'), ('adjust', 'Adjusted (stocktake)')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.asset')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='schools.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.campus')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='schools.school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Reorder point. Reached when quantity drops to this level.')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.asset')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='schools.campus')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='schools.school')),
            ],
            options={
                'ordering': ('asset__name',),
                'constraints': [models.UniqueConstraint(fields=('campus', 'asset'), name='unique_stock_level_per_campus_asset')],
            },
        ),
    ]
