# Generated by Django 6.1 on 2026-08-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_merge_schools_leaves'),
        ('students', '0009_add_institution_to_all_models'),
        ('teachers', '0007_add_institution_to_all_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField(default=10, help_text='Maximum score a student can receive.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='schools.campus')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='schools.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homework', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schools.school')),
                ('section', models.ForeignKey(blank=True, help_text='Leave empty to assign the whole class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='schools.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='schools.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_given', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=12)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_homework', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('homework', 'student'), name='unique_submission_per_homework_student')],
            },
        ),
    ]
