# Generated by Django 6.1 on 2026-08-29 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Campus where this contract applies (optional, defaults to employee's primary campus)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_contracts', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employmentevent',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Current campus for this event (for filtering)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_events', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='employmentevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workloadassignment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workload_assignments', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='workloadassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='empdoc_emp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['campus', 'expiry_date'], name='empdoc_campus_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['employee', 'status'], name='contract_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['campus', 'status'], name='contract_campus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentevent',
            index=models.Index(fields=['employee', 'effective_date'], name='empevent_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentevent',
            index=models.Index(fields=['campus', 'effective_date'], name='empevent_campus_date_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'review_date'], name='perfrev_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['campus', 'review_date'], name='perfrev_campus_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadassignment',
            index=models.Index(fields=['employee', 'academic_year', 'status'], name='workload_emp_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadassignment',
            index=models.Index(fields=['campus', 'academic_year'], name='workload_campus_year_idx'),
        ),
    ]
