# Generated by Django 6.1 on 2026-08-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_confirmation_date_employee_employment_type_and_more'),
        ('hr', '0002_employeedocument_campus_employmentcontract_campus_and_more'),
    ]

    operations = [
    ]
