# Generated by Django 6.1 on 2026-08-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_subjectoffering'),
        ('students', '0002_alter_enrollment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='schools.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='schools.campus')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='schools.class')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='schools.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day')],
            },
        ),
    ]
