# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_twofa_enabled_user_twofa_secret'),
        ('attendance', '0001_initial'),
        ('students', '0009_add_institution_to_all_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused'), ('half_day', 'Half Day')], max_length=20)),
                ('to_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused'), ('half_day', 'Half Day')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendance')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='students.student')),
            ],
            options={
                'ordering': ['-corrected_at'],
                'indexes': [
                    models.Index(fields=['attendance', '-corrected_at'], name='att_corr_att_corr_at_idx'),
                    models.Index(fields=['student', 'corrected_by'], name='att_corr_stu_by_idx'),
                ],
            },
        ),
    ]
