# Generated by Django 6.1 on 2026-08-29 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecorrection_and_more'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('students', '0010_progressionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['campus', 'date', 'status'], name='att_campus_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_obj', 'section', 'date'], name='att_class_section_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_year', 'date'], name='att_year_date_idx'),
        ),
    ]
