# Generated by Django 6.1 on 2026-09-20 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_att_campus_date_status_idx_and_more'),
        ('schools', '0029_class_class_unit_status_idx_and_more'),
        ('students', '0014_studentdocument_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='att_student_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='att_student_date_idx'),
        ),
    ]
