# Generated by Django 6.1 on 2026-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='employee_id',
            new_name='employee_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('subject_teacher', 'Subject Teacher'), ('class_teacher', 'Class Teacher'), ('coordinator', 'Coordinator')], default='subject_teacher', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resigned', 'Resigned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
