# Generated by Django 6.1 on 2026-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacherassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherassignment',
            name='unique_teacher_assignment',
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='TeacherAssignment',
        ),
    ]
