# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_institution_to_all_models'),
        ('schools', '0008_add_institution_to_all_models'),
        ('teachers', '0006_teacher_membership_primary_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('institution', 'employee_number'), name='unique_teacher_employee_number_per_institution'),
        ),
    ]
