# Generated by Django 6.1 on 2026-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number or IBAN for payroll transfers.', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
