# Generated by Django 6.1 on 2026-08-29 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffattendance_deleted_at_and_more'),
        ('schools', '0019_subjectoffering_is_compulsory_and_more'),
        ('teachers', '0008_teacher_account_number_teacher_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['institution', 'status'], name='teacher_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['primary_campus', 'status'], name='teacher_campus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name', 'first_name'], name='teacher_name_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'academic_year', 'status'], name='tassign_teacher_yr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['campus', 'class_obj', 'section', 'status'], name='tassign_campus_cls_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['academic_year', 'status'], name='tassign_year_status_idx'),
        ),
    ]
