# Generated by Django 6.1 on 2026-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_academicyear_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('language', 'Language'), ('religious', 'Religious'), ('computer', 'Computer'), ('social_science', 'Social Science'), ('elective', 'Elective')], default='general', max_length=30)),
                ('practical_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
