# Generated by Django 6.1 on 2026-08-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_add_institution_to_all_models'),
        ('schools', '0008_school_white_label'),
    ]

    operations = [
    ]
