# Generated by Django 6.1 on 2026-08-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_merge_schools_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled module keys from schools.modules.ALL_MODULES. An empty list means ALL modules are enabled (backwards compatible default).'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
