# Generated by Django 6.1 on 2026-08-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_enabled_modules_alter_academicyear_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='date_format',
            field=models.CharField(choices=[('dd-mm-yyyy', '31-12-2026'), ('dd MMM yyyy', '31 Dec 2026'), ('mm/dd/yyyy', '12/31/2026'), ('yyyy-mm-dd', '2026-12-31')], default='dd-mm-yyyy', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='Per-school from address override for outgoing emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='White-label display name on outgoing emails.', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'اردو')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='short_name',
            field=models.CharField(blank=True, help_text='Compact name used in tight UI spaces.', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='List of working day keys, e.g. ["mon","tue","wed","thu","fri"]. Empty = Mon-Fri.'),
        ),
    ]
