# Generated by Django 6.1 on 2026-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_schoolsettings_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain for this school (e.g., school.example.com). Used for domain-based tenant resolution.', max_length=255, null=True, unique=True),
        ),
    ]
