# Generated by Django 6.1 on 2026-08-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_campus_custom_domain'),
        ('teachers', '0008_teacher_account_number_teacher_bank_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicunit',
            options={'ordering': ['name'], 'verbose_name_plural': 'Academic Units'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['class_obj__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subjectoffering',
            options={'ordering': ['class_obj__name', 'subject__name']},
        ),
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='unique_academic_year_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_per_class',
        ),
        migrations.RemoveConstraint(
            model_name='subjectoffering',
            name='unique_subject_offering',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_per_academic_year',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='secondary_color',
            new_name='second_color',
        ),
        migrations.RemoveField(
            model_name='academicunit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academicunit',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='academicunit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='class',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='enabled_modules',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_required',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain for this school (e.g., school.example.com). Used for domain-based tenant resolution.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='schools.academicyear'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='schools.class'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='schools.subject'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_year'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('academic_year', 'class_obj', 'subject'), name='unique_subject_offering_per_class_per_year'),
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_at',
        ),
    ]
