# Generated by Django 6.1 on 2026-08-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_academicunit_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='second_color',
            new_name='secondary_color',
        ),
    ]
