# Generated by Django 6.1 on 2026-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_rename_second_color_schoolsettings_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled module keys from schools.modules.ALL_MODULES. An empty list means ALL modules are enabled (backwards compatible default).'),
        ),
    ]
