# Generated by Django 6.1 on 2026-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_add_missing_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=20),
        ),
    ]
