# Generated by Django 6.1 on 2026-08-29 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('teachers', '0008_teacher_account_number_teacher_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='is_compulsory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='periods_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='schools.section'),
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('event', 'School Event'), ('meeting', 'Meeting'), ('holiday_break', 'Holiday Break'), ('exam_period', 'Exam Period'), ('assignment_due', 'Assignment Due'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_for_all_campuses', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='schools.academicyear')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='schools.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendar_events', to='schools.school')),
                ('target_classes', models.ManyToManyField(blank=True, related_name='calendar_events', to='schools.class')),
                ('target_sections', models.ManyToManyField(blank=True, related_name='calendar_events', to='schools.section')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['institution', 'start_date', 'end_date'], name='acal_inst_date_idx'), models.Index(fields=['campus', 'start_date', 'end_date'], name='acal_campus_date_idx'), models.Index(fields=['academic_year', 'start_date'], name='acal_year_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='schools.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='schools.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'constraints': [models.UniqueConstraint(fields=('section', 'academic_year'), name='unique_class_teacher_per_section_per_year')],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='schools.school')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subject_groups', to='schools.subject')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_subject_group_code_per_institution')],
            },
        ),
    ]
