# Generated by Django 6.1 on 2026-08-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_subjectoffering_is_compulsory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
