# Generated by Django 6.1 on 2026-09-04 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_alter_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='schools.school'),
        ),
    ]
