# Generated by Django 6.1 on 2026-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_subjectoffering_institution'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('class_obj', 'name'), name='unique_section_name_per_class'),
        ),
    ]
