# Generated by Django 6.1 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


def populate_campus_from_class(apps, schema_editor):
    """Populate campus FK from class_obj.unit.campus for existing SubjectOfferings."""
    SubjectOffering = apps.get_model('schools', 'SubjectOffering')
    for so in SubjectOffering.objects.all():
        if so.class_obj_id and so.class_obj.unit_id and so.class_obj.unit.campus_id:
            so.campus_id = so.class_obj.unit.campus_id
            so.save(update_fields=['campus_id'])


def reverse_populate_campus(apps, schema_editor):
    """No-op reverse - we don't want to clear the campus data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_section_unique_section_name_per_class'),
    ]

    operations = [
        # Step 1: Add nullable campus FK
        migrations.AddField(
            model_name='subjectoffering',
            name='campus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subject_offerings',
                to='schools.campus',
            ),
        ),
        # Step 2: Data migration to populate campus from class_obj.unit.campus
        migrations.RunPython(
            populate_campus_from_class,
            reverse_populate_campus,
        ),
    ]