# Generated by Django 6.1 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_subjectoffering_campus'),
    ]

    operations = [
        # Step 3: Make campus FK non-nullable after data migration
        migrations.AlterField(
            model_name='subjectoffering',
            name='campus',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subject_offerings',
                to='schools.campus',
            ),
        ),
    ]