# Generated by Django 6.1 on 2026-09-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_subjectoffering_campus_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectoffering',
            name='campus',
        ),
    ]
