# Generated by Django 6.1 on 2026-09-13 08:30

import re

from django.db import migrations, models


def copy_primary_color_to_theme_color(apps, schema_editor):
    """Safe default for existing rows: keep the exact current appearance.

    The app shell previously derived its accent from ``primary_color``.
    Backfill the new ``theme_color`` from it so schools that already
    customized their colors do not change appearance after the migration.
    Only strict #RRGGBB values are carried over; anything else (legacy
    named colors or unsafe strings) falls back to the safe default.
    """
    SchoolSettings = apps.get_model("schools", "SchoolSettings")
    hex_color = re.compile(r"^#[0-9A-Fa-f]{6}$")

    for row in SchoolSettings.objects.all().iterator():
        source = (row.primary_color or "").strip()

        if hex_color.match(source):
            row.theme_color = source
        else:
            row.theme_color = "#1a73e8"

        row.save(update_fields=["theme_color"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_subjectoffering_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='theme_color',
            field=models.CharField(default='#1a73e8', help_text='Application theme color (strict hex, #RRGGBB).', max_length=7),
        ),
        migrations.RunPython(
            copy_primary_color_to_theme_color,
            reverse_code=noop,
        ),
    ]