# Generated by Django 6.1 on 2026-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_schoolsettings_theme_color'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['unit', 'status'], name='class_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['class_obj', 'status'], name='section_class_status_idx'),
        ),
    ]
