# Generated by Django 6.1 on 2026-09-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_class_class_unit_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['school', 'status'], name='campus_school_status_idx'),
        ),
    ]
