# Generated by Django 6.1 on 2026-09-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_fix_campus_delete_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='schools.campus'),
        ),
    ]
