# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_merge_messagetemplate_seed'),
        ('schools', '0008_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='schools.school'),
        ),
        migrations.AddField(
            model_name='message',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schools.school'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='schools.school'),
        ),
        migrations.AddField(
            model_name='notification',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs_tenant', to='schools.school'),
        ),
    ]
