# Generated by Django 6.1 on 2026-08-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fee_reminder', 'Fee Reminder'), ('absence_alert', 'Absence Alert'), ('result_published', 'Result Published')], max_length=24)),
                ('reference', models.CharField(help_text="Stable per-target key, e.g. 'fee:{student}:{isoweek}'.", max_length=120)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('recipient', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'reference', 'channel'), name='unique_dispatch_per_kind_ref_channel')],
            },
        ),
    ]
