# Generated by Django 6.1 on 2026-08-28 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_notificationdispatch'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-app')], max_length=10)),
                ('kind', models.CharField(blank=True, help_text='Dispatch kind, e.g. fee_reminder / result_published.', max_length=24)),
                ('reference', models.CharField(blank=True, help_text='Stable per-target key for idempotency, e.g. result:{id}.', max_length=120)),
                ('to_address', models.CharField(blank=True, help_text='Phone number (sms) or email address (email).', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the notification should first be delivered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='schools.school')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='qn_due_idx'), models.Index(fields=['channel', 'kind'], name='qn_channel_kind_idx')],
            },
        ),
    ]
