# Generated by Django 6.1 on 2026-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_queuednotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdispatch',
            name='job_type',
            field=models.CharField(choices=[('notification', 'Notification'), ('automation', 'Automation Action'), ('import', 'Data Import'), ('custom', 'Custom Job')], default='notification', help_text='Type of background job.', max_length=24),
        ),
        migrations.AlterField(
            model_name='queuednotification',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10),
        ),
    ]
