# Generated by Django 6.1 on 2026-08-29 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_roleassignment_role'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('students', '0009_add_institution_to_all_models'),
        ('teachers', '0008_teacher_account_number_teacher_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff')], max_length=20)),
                ('card_number', models.CharField(max_length=40)),
                ('barcode_data', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='digital_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='schools.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_id_cards', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='schools.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='accounts.staffprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'card_number'), name='unique_card_number_per_institution')],
            },
        ),
    ]
