from django.urls import path

from .views import (
    DepartmentListCreateView,
    DepartmentDetailView,
    DesignationListCreateView,
    DesignationDetailView,
    EmployeeContractListCreateView,
    EmployeeDetailView,
    EmployeeDocumentListCreateView,
    EmployeeListView,
    EmployeeReviewListCreateView,
    EmployeeWorkloadListCreateView,
    EmploymentEventCreateView,
    EmploymentEventListView,
    LeaveTypeListCreateView,
    LeaveTypeDetailView,
    LeavePolicyListCreateView,
    LeavePolicyDetailView,
    LeaveBalanceListView,
    LeaveBalanceDetailView,
    LeaveRequestListCreateView,
    LeaveRequestDetailView,
    LeaveRequestActionView,
    AllowanceListCreateView,
    AllowanceDetailView,
    DeductionListCreateView,
    DeductionDetailView,
    BonusListCreateView,
    BonusDetailView,
    OvertimeListCreateView,
    OvertimeDetailView,
    OvertimeActionView,
    LoanListCreateView,
    LoanDetailView,
    LoanActionView,
    AdvanceListCreateView,
    AdvanceDetailView,
    AdvanceActionView,
    SalaryRevisionListCreateView,
    SalaryRevisionDetailView,
    PayrollPeriodListCreateView,
    PayrollPeriodDetailView,
    PayrollPeriodActionView,
    ExitClearanceListCreateView,
    ExitClearanceDetailView,
    ClearanceItemActionView,
    JobPositionListCreateView,
    JobPositionDetailView,
    CandidateListCreateView,
    CandidateDetailView,
    ApplicationListCreateView,
    ApplicationDetailView,
    InterviewListCreateView,
    InterviewDetailView,
    InterviewActionView,
    EmployeeListView,
    EmployeeDetailView,
    EmployeeContractListCreateView,
    EmployeeDocumentListCreateView,
    EmployeeWorkloadListCreateView,
    EmployeeReviewListCreateView,
    EmploymentEventCreateView,
    EmploymentEventListView,
)

urlpatterns = [
    # Department & Designation
    path("departments/", DepartmentListCreateView.as_view(), name="department-list"),
    path("departments/<int:pk>/", DepartmentDetailView.as_view(), name="department-detail"),
    path("designations/", DesignationListCreateView.as_view(), name="designation-list"),
    path("designations/<int:pk>/", DesignationDetailView.as_view(), name="designation-detail"),

    # Employees
    path("employees/", EmployeeListView.as_view(), name="employee-list"),
    path("employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("employees/<int:employee_id>/contracts/", EmployeeContractListCreateView.as_view(), name="employee-contract-list"),
    path("employees/<int:employee_id>/documents/", EmployeeDocumentListCreateView.as_view(), name="employee-document-list"),
    path("employees/<int:employee_id>/workload/", EmployeeWorkloadListCreateView.as_view(), name="employee-workload-list"),
    path("employees/<int:employee_id>/reviews/", EmployeeReviewListCreateView.as_view(), name="employee-review-list"),

    # Leave Management
    path("leave-types/", LeaveTypeListCreateView.as_view(), name="leave-type-list"),
    path("leave-types/<int:pk>/", LeaveTypeDetailView.as_view(), name="leave-type-detail"),
    path("leave-policies/", LeavePolicyListCreateView.as_view(), name="leave-policy-list"),
    path("leave-policies/<int:pk>/", LeavePolicyDetailView.as_view(), name="leave-policy-detail"),
    path("leave-balances/", LeaveBalanceListView.as_view(), name="leave-balance-list"),
    path("leave-balances/<int:pk>/", LeaveBalanceDetailView.as_view(), name="leave-balance-detail"),
    path("leave-requests/", LeaveRequestListCreateView.as_view(), name="leave-request-list"),
    path("leave-requests/<int:pk>/", LeaveRequestDetailView.as_view(), name="leave-request-detail"),
    path("leave-requests/<int:pk>/<str:action>/", LeaveRequestActionView.as_view(), name="leave-request-action"),

    # Salary Components
    path("allowances/", AllowanceListCreateView.as_view(), name="allowance-list"),
    path("allowances/<int:pk>/", AllowanceDetailView.as_view(), name="allowance-detail"),
    path("deductions/", DeductionListCreateView.as_view(), name="deduction-list"),
    path("deductions/<int:pk>/", DeductionDetailView.as_view(), name="deduction-detail"),
    path("bonuses/", BonusListCreateView.as_view(), name="bonus-list"),
    path("bonuses/<int:pk>/", BonusDetailView.as_view(), name="bonus-detail"),
    path("overtime/", OvertimeListCreateView.as_view(), name="overtime-list"),
    path("overtime/<int:pk>/", OvertimeDetailView.as_view(), name="overtime-detail"),
    path("overtime/<int:pk>/<str:action>/", OvertimeActionView.as_view(), name="overtime-action"),

    # Financial
    path("loans/", LoanListCreateView.as_view(), name="loan-list"),
    path("loans/<int:pk>/", LoanDetailView.as_view(), name="loan-detail"),
    path("loans/<int:pk>/<str:action>/", LoanActionView.as_view(), name="loan-action"),
    path("advances/", AdvanceListCreateView.as_view(), name="advance-list"),
    path("advances/<int:pk>/", AdvanceDetailView.as_view(), name="advance-detail"),
    path("advances/<int:pk>/<str:action>/", AdvanceActionView.as_view(), name="advance-action"),
    path("salary-revisions/", SalaryRevisionListCreateView.as_view(), name="salary-revision-list"),
    path("salary-revisions/<int:pk>/", SalaryRevisionDetailView.as_view(), name="salary-revision-detail"),

    # Payroll Periods
    path("payroll-periods/", PayrollPeriodListCreateView.as_view(), name="payroll-period-list"),
    path("payroll-periods/<int:pk>/", PayrollPeriodDetailView.as_view(), name="payroll-period-detail"),
    path("payroll-periods/<int:pk>/<str:action>/", PayrollPeriodActionView.as_view(), name="payroll-period-action"),

    # Exit Clearance
    path("exit-clearances/", ExitClearanceListCreateView.as_view(), name="exit-clearance-list"),
    path("exit-clearances/<int:pk>/", ExitClearanceDetailView.as_view(), name="exit-clearance-detail"),
    path("clearance-items/<int:pk>/<str:action>/", ClearanceItemActionView.as_view(), name="clearance-item-action"),

    # Recruitment
    path("job-positions/", JobPositionListCreateView.as_view(), name="job-position-list"),
    path("job-positions/<int:pk>/", JobPositionDetailView.as_view(), name="job-position-detail"),
    path("candidates/", CandidateListCreateView.as_view(), name="candidate-list"),
    path("candidates/<int:pk>/", CandidateDetailView.as_view(), name="candidate-detail"),
    path("applications/", ApplicationListCreateView.as_view(), name="application-list"),
    path("applications/<int:pk>/", ApplicationDetailView.as_view(), name="application-detail"),
    path("interviews/", InterviewListCreateView.as_view(), name="interview-list"),
    path("interviews/<int:pk>/", InterviewDetailView.as_view(), name="interview-detail"),
    path("interviews/<int:pk>/<str:action>/", InterviewActionView.as_view(), name="interview-action"),

    # Employment Events
    path("employment-events/", EmploymentEventListView.as_view(), name="employment-event-list"),
    path("employment-events/create/", EmploymentEventCreateView.as_view(), name="employment-event-create"),

    # Employee Details (with related data)
    path("employees/<int:pk>/detail/", EmployeeDetailView.as_view(), name="employee-detail-full"),
    path("employees/<int:employee_id>/contracts/", EmployeeContractListCreateView.as_view(), name="employee-contract-list"),
    path("employees/<int:employee_id>/documents/", EmployeeDocumentListCreateView.as_view(), name="employee-document-list"),
    path("employees/<int:employee_id>/workload/", EmployeeWorkloadListCreateView.as_view(), name="employee-workload-list"),
    path("employees/<int:employee_id>/reviews/", EmployeeReviewListCreateView.as_view(), name="employee-review-list"),
    path("employment-events/", EmploymentEventListView.as_view(), name="employment-event-list"),
    path("employment-events/create/", EmploymentEventCreateView.as_view(), name="employment-event-create"),
]