# Generated by Django 6.1 on 2026-08-29 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('id_number', models.CharField(blank=True, help_text='National ID / CNIC if provided at the gate.', max_length=50)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('meeting_party', models.CharField(blank=True, help_text='Who they came to see, e.g. Principal - Mr. Khan.', max_length=120)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('badge_number', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='schools.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='schools.school')),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['institution', 'status'], name='visitors_vi_institu_035f18_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'badge_number'), name='unique_visitor_badge_per_institution')],
            },
        ),
    ]
