from django.urls import path

from .certificates import StudentCertificatePdfView
from .public_views import (
    PublicAdmissionApplyView,
    PublicAdmissionOptionsView,
)
from .transcripts import StudentTranscriptPdfView
from .views import (
    AcademicHistoryDetailView,
    AcademicHistoryListView,
    AdmissionApplicationAcceptView,
    AdmissionApplicationDetailView,
    AdmissionApplicationListCreateView,
    AdmissionApplicationReviewView,
    CampusTransferApproveView,
    CampusTransferCancelView,
    CampusTransferCompleteView,
    CampusTransferDetailView,
    CampusTransferListCreateView,
    CampusTransferRejectView,
    CampusTransferReverseView,
    GuardianListCreateView,
    GuardianDetailView,
    GuardianMyView,
    InquiryConvertView,
    InquiryDetailView,
    InquiryListCreateView,
    SectionTransferApproveView,
    SectionTransferCancelView,
    SectionTransferCompleteView,
    SectionTransferDetailView,
    SectionTransferListCreateView,
    SectionTransferRejectView,
    Student360View,
    StudentAlumniDetailView,
    StudentGraduateView,
    StudentListCreateView,
    StudentDetailView,
    StudentGuardianListCreateView,
    StudentLifecycleActionView,
    StudentLifecycleListView,
    StudentLeaveRequestActionView,
    StudentLeaveRequestListCreateView,
    StudentMyView,
    StudentDocumentListCreateView,
    StudentDocumentDetailView,
    EnrollmentListCreateView,
    EnrollmentDetailView,
    PromotionView,
    StudentActivateView,
    StudentWithdrawView,
    StudentGraduateView,
    TransferCertificateCancelView,
    TransferCertificateDetailView,
    TransferCertificateIssueView,
    TransferCertificateListCreateView,
    TransferCertificateVerifyView,
)


urlpatterns = [
    path(
        "admissions/",
        AdmissionApplicationListCreateView.as_view(),
        name="admission-list",
    ),
    path(
        "<int:pk>/360/",
        Student360View.as_view(),
        name="student-360",
    ),
    # Campus Transfers
    path(
        "campus-transfers/",
        CampusTransferListCreateView.as_view(),
        name="campus-transfer-list",
    ),
    path(
        "campus-transfers/<int:pk>/",
        CampusTransferDetailView.as_view(),
        name="campus-transfer-detail",
    ),
    path(
        "campus-transfers/<int:pk>/approve/",
        CampusTransferApproveView.as_view(),
        name="campus-transfer-approve",
    ),
    path(
        "campus-transfers/<int:pk>/reject/",
        CampusTransferRejectView.as_view(),
        name="campus-transfer-reject",
    ),
    path(
        "campus-transfers/<int:pk>/complete/",
        CampusTransferCompleteView.as_view(),
        name="campus-transfer-complete",
    ),
    path(
        "campus-transfers/<int:pk>/cancel/",
        CampusTransferCancelView.as_view(),
        name="campus-transfer-cancel",
    ),
    path(
        "campus-transfers/<int:pk>/reverse/",
        CampusTransferReverseView.as_view(),
        name="campus-transfer-reverse",
    ),
    # Section Transfers
    path(
        "section-transfers/",
        SectionTransferListCreateView.as_view(),
        name="section-transfer-list",
    ),
    path(
        "section-transfers/<int:pk>/",
        SectionTransferDetailView.as_view(),
        name="section-transfer-detail",
    ),
    path(
        "section-transfers/<int:pk>/approve/",
        SectionTransferApproveView.as_view(),
        name="section-transfer-approve",
    ),
    path(
        "section-transfers/<int:pk>/reject/",
        SectionTransferRejectView.as_view(),
        name="section-transfer-reject",
    ),
    path(
        "section-transfers/<int:pk>/complete/",
        SectionTransferCompleteView.as_view(),
        name="section-transfer-complete",
    ),
    path(
        "section-transfers/<int:pk>/cancel/",
        SectionTransferCancelView.as_view(),
        name="section-transfer-cancel",
    ),
    # Alumni
    path(
        "alumni/",
        StudentAlumniDetailView.as_view(),
        name="student-alumni-detail",
    ),
    path(
        "alumni/<int:pk>/",
        StudentAlumniDetailView.as_view(),
        name="student-alumni-detail-pk",
    ),
    # Graduation/Withdrawal/Activation
    path(
        "<int:pk>/graduate/",
        StudentGraduateView.as_view(),
        name="student-graduate",
    ),
    path(
        "<int:pk>/withdraw/",
        StudentWithdrawView.as_view(),
        name="student-withdraw",
    ),
    path(
        "<int:pk>/activate/",
        StudentActivateView.as_view(),
        name="student-activate",
    ),
    path(
        "<int:pk>/360/",
        Student360View.as_view(),
        name="student-360",
    ),
    path(
        "admissions/<int:pk>/",
        AdmissionApplicationDetailView.as_view(),
        name="admission-detail",
    ),
    path(
        "admissions/<int:pk>/review/",
        AdmissionApplicationReviewView.as_view(),
        name="admission-review",
    ),
    path(
        "admissions/<int:pk>/accept/",
        AdmissionApplicationAcceptView.as_view(),
        name="admission-accept",
    ),
    path(
        "admissions/public/options/",
        PublicAdmissionOptionsView.as_view(),
        name="public-admission-options",
    ),
    path(
        "admissions/public/apply/",
        PublicAdmissionApplyView.as_view(),
        name="public-admission-apply",
    ),
    path(
        "inquiries/",
        InquiryListCreateView.as_view(),
        name="inquiry-list",
    ),
    path(
        "inquiries/<int:pk>/",
        InquiryDetailView.as_view(),
        name="inquiry-detail",
    ),
    path(
        "inquiries/<int:pk>/convert/",
        InquiryConvertView.as_view(),
        name="inquiry-convert",
    ),
    path(
        "academic-history/",
        AcademicHistoryListView.as_view(),
        name="academic-history-list",
    ),
    path(
        "academic-history/<int:pk>/",
        AcademicHistoryDetailView.as_view(),
        name="academic-history-detail",
    ),
    path(
        "transfer-certificates/",
        TransferCertificateListCreateView.as_view(),
        name="transfer-certificate-list",
    ),
    path(
        "transfer-certificates/<int:pk>/",
        TransferCertificateDetailView.as_view(),
        name="transfer-certificate-detail",
    ),
    path(
        "transfer-certificates/<int:pk>/issue/",
        TransferCertificateIssueView.as_view(),
        name="transfer-certificate-issue",
    ),
    path(
        "transfer-certificates/<int:pk>/cancel/",
        TransferCertificateCancelView.as_view(),
        name="transfer-certificate-cancel",
    ),
    path(
        "transfer-certificates/verify/<str:code>/",
        TransferCertificateVerifyView.as_view(),
        name="transfer-certificate-verify",
    ),
    path(
        "guardian-links/",
        StudentGuardianListCreateView.as_view(),
        name="student-guardian-list",
    ),
    path(
        "lifecycle/",
        StudentLifecycleListView.as_view(),
        name="student-lifecycle-list",
    ),
    path(
        "leave/",
        StudentLeaveRequestListCreateView.as_view(),
        name="student-leave-list",
    ),
    path(
        "leave/<int:pk>/action/",
        StudentLeaveRequestActionView.as_view(),
        name="student-leave-action",
    ),
    path(
        "promotions/",
        PromotionView.as_view(),
        name="student-promotion",
    ),
    path(
        "",
        StudentListCreateView.as_view(),
        name="student-list",
    ),

    path(
        "me/",
        StudentMyView.as_view(),
        name="student-my",
    ),

    path(
        "guardians/",
        GuardianListCreateView.as_view(),
        name="guardian-list",
    ),

    path(
        "guardians/me/",
        GuardianMyView.as_view(),
        name="guardian-my",
    ),

    path(
        "guardians/<int:pk>/",
        GuardianDetailView.as_view(),
        name="guardian-detail",
    ),

    path(
        "documents/",
        StudentDocumentListCreateView.as_view(),
        name="document-list",
    ),

    path(
        "documents/<int:pk>/",
        StudentDocumentDetailView.as_view(),
        name="document-detail",
    ),

    path(
        "enrollments/",
        EnrollmentListCreateView.as_view(),
        name="enrollment-list",
    ),

    path(
        "<int:pk>/certificate/<str:cert_type>/",
        StudentCertificatePdfView.as_view(),
        name="student-certificate",
    ),

    path(
        "<int:pk>/transcript.pdf",
        StudentTranscriptPdfView.as_view(),
        name="student-transcript",
    ),

    path(
        "enrollments/<int:pk>/",
        EnrollmentDetailView.as_view(),
        name="enrollment-detail",
    ),

    path(
        "<int:pk>/lifecycle/",
        StudentLifecycleActionView.as_view(),
        name="student-lifecycle-action",
    ),

    path(
        "<int:pk>/",
        StudentDetailView.as_view(),
        name="student-detail",
    ),
]
