# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_add_institution_to_all_models'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='unique_period_number',
        ),
        migrations.AddField(
            model_name='period',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('institution', 'number'), name='unique_period_number_per_institution'),
        ),
    ]
