# Generated by Django 6.1 on 2026-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('settings_change', 'Settings Change'), ('password_reset', 'Password Reset'), ('grade_publish', 'Grade Publish'), ('grade_amendment', 'Grade Amendment'), ('payment', 'Payment'), ('payment_reversal', 'Payment Reversal'), ('invoice', 'Invoice'), ('export', 'Export'), ('other', 'Other')], max_length=30),
        ),
    ]
