# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
        ('schools', '0008_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='schools.school'),
        ),
    ]
