# Generated by Django 6.1 on 2026-08-29 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_add_institution_to_all_models'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['institution', 'timestamp'], name='audit_inst_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_model_obj_idx'),
        ),
    ]
