# Generated by Django 6.1 on 2026-08-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auditlog_audit_inst_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('institution_switched', 'Institution Switched'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('settings_change', 'Settings Change'), ('password_reset', 'Password Reset'), ('grade_publish', 'Grade Publish'), ('grade_amendment', 'Grade Amendment'), ('payment', 'Payment'), ('payment_reversal', 'Payment Reversal'), ('payment_refund', 'Payment Refund'), ('invoice', 'Invoice'), ('expense_posted', 'Expense Posted'), ('concession_approved', 'Concession Approved'), ('staff_leave_approved', 'Staff Leave Approved'), ('staff_leave_rejected', 'Staff Leave Rejected'), ('other', 'Other'), ('student_transfer_initiated', 'Student Transfer Initiated'), ('student_transfer_approved', 'Student Transfer Approved'), ('student_transfer_rejected', 'Student Transfer Rejected')], max_length=30),
        ),
    ]
