# Generated by Django 6.1 on 2026-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('institution_switched', 'Institution Switched'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('settings_change', 'Settings Change'), ('password_reset', 'Password Reset'), ('grade_publish', 'Grade Publish'), ('grade_amendment', 'Grade Amendment'), ('payment', 'Payment'), ('payment_reversal', 'Payment Reversal'), ('payment_refund', 'Payment Refund'), ('invoice', 'Invoice'), ('expense_posted', 'Expense Posted'), ('concession_approved', 'Concession Approved'), ('staff_leave_approved', 'Staff Leave Approved'), ('staff_leave_rejected', 'Staff Leave Rejected'), ('other', 'Other'), ('student_transfer_initiated', 'Student Transfer Initiated'), ('student_transfer_approved', 'Student Transfer Approved'), ('student_transfer_rejected', 'Student Transfer Rejected'), ('subscription_changed', 'Subscription Changed'), ('feature_flag_changed', 'Feature Flag Changed'), ('role_change', 'Role Changed'), ('brute_force_detected', 'Brute Force Detected'), ('api_key_created', 'API Key Created'), ('ai_ask', 'AI Ask'), ('ai_search', 'AI Search'), ('ai_insight', 'AI Insight'), ('ai_anomaly', 'AI Anomaly Scan'), ('ai_draft', 'AI Communication Draft')], max_length=30),
        ),
    ]
