# Generated by Django 6.1 on 2026-09-18 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_auditlog_action'),
        ('schools', '0028_schoolsettings_theme_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField(help_text='The document in which the violation occurred.', max_length=2000)),
                ('referrer', models.URLField(blank=True, help_text='The referrer of the document.', max_length=2000, null=True)),
                ('blocked_uri', models.URLField(blank=True, help_text='The blocked resource URI (sanitized: query string removed).', max_length=2000, null=True)),
                ('violated_directive', models.CharField(help_text='The CSP directive that was violated.', max_length=255)),
                ('effective_directive', models.CharField(blank=True, help_text='The effective directive that caused the violation.', max_length=255)),
                ('original_policy', models.TextField(blank=True, help_text='The original CSP policy that was violated.')),
                ('disposition', models.CharField(choices=[('enforce', 'Enforce'), ('report', 'Report')], default='enforce', help_text='Whether the policy was enforced or report-only.', max_length=20)),
                ('script_sample', models.CharField(blank=True, help_text='Sample of the inline script that caused the violation (truncated).', max_length=80)),
                ('source_file', models.URLField(blank=True, help_text='The file where the violation occurred.', max_length=2000, null=True)),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='Line number in the source file where the violation occurred.', null=True)),
                ('column_number', models.PositiveIntegerField(blank=True, help_text='Column number in the source file where the violation occurred.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='The user agent string of the browser.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client.', null=True)),
                ('status_code', models.PositiveIntegerField(default=0, help_text='HTTP status code of the blocked resource (if applicable).')),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource that was blocked (script, style, image, etc.).', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the violation was reported.')),
                ('institution', models.ForeignKey(blank=True, help_text='Institution context derived from request (if available).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csp_violations', to='schools.school')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who triggered the violation (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csp_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['institution', 'timestamp'], name='csp_viol_inst_time_idx'), models.Index(fields=['violated_directive', 'timestamp'], name='csp_viol_directive_idx'), models.Index(fields=['blocked_uri', 'timestamp'], name='csp_viol_blocked_idx'), models.Index(fields=['user', 'timestamp'], name='csp_viol_user_time_idx')],
            },
        ),
    ]
