# Generated by Django 6.1 on 2026-08-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_alter_enrollment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
            ],
            options={
                'ordering': ['exam', 'position', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximum_marks', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=3)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_entries', to='exams.examsubject')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_entries', to='reportcards.reportcard')),
            ],
            options={
                'ordering': ['exam_subject__subject__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_report_card_per_student_exam'),
        ),
        migrations.AddConstraint(
            model_name='reportcardsubject',
            constraint=models.UniqueConstraint(fields=('report_card', 'exam_subject'), name='unique_report_card_subject'),
        ),
    ]
