# Generated by Django 6.1 on 2026-08-10 14:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentresult_is_absent'),
        ('reportcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used for automated grade calculation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='GradeAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('previous_grade', models.CharField(blank=True, max_length=3)),
                ('new_grade', models.CharField(blank=True, max_length=3)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_amendments', to=settings.AUTH_USER_MODEL)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='exams.examsubject')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='reportcards.reportcard')),
                ('student_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='amendment', to='exams.studentresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=3)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('minimum_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='reportcards.gradescale')),
            ],
            options={
                'ordering': ['-minimum_percentage'],
                'constraints': [models.UniqueConstraint(fields=('scale', 'letter_grade'), name='unique_band_per_scale'), models.UniqueConstraint(fields=('scale', 'minimum_percentage'), name='unique_min_per_scale')],
            },
        ),
    ]
