# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0003_seed_default_grade_scale'),
        ('schools', '0008_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_grade_scale_name_per_institution'),
        ),
    ]
