# Generated by Django 6.1 on 2026-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0004_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
    ]
