# Generated by Django 6.1 on 2026-09-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_studentresult_result_student_idx'),
        ('reportcards', '0005_alter_reportcard_status'),
        ('students', '0014_studentdocument_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student'], name='reportcard_student_idx'),
        ),
    ]
