# Generated by Django 6.1 on 2026-08-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_confirmation_date_employee_employment_type_and_more'),
        ('payroll', '0001_initial'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('component_type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_basic', 'Percentage of Basic'), ('percent_gross', 'Percentage of Gross'), ('percent_net', 'Percentage of Net'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour')], max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_basic', 'Percentage of Basic'), ('percent_gross', 'Percentage of Gross'), ('percent_net', 'Percentage of Net'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('applicable_to', models.JSONField(blank=True, default=list, help_text='List of designation codes this component applies to')),
                ('condition', models.TextField(blank=True, help_text='Python expression for conditional application')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-year', '-month', 'employee__employee_number']},
        ),
        migrations.RemoveConstraint(
            model_name='payrollrecord',
            name='unique_teacher_payroll_period',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='teacher',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='component_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of each component'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='gross_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='hr.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='schools.school'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'payroll_period'), name='unique_employee_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_salary_structure_code_per_institution'),
        ),
        migrations.AddField(
            model_name='salarycomponenttemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_component_templates', to='schools.school'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure'),
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='teacher',
        ),
        migrations.AddConstraint(
            model_name='salarycomponenttemplate',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_component_template_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'code'), name='unique_component_code_per_structure'),
        ),
    ]
