# Generated by Django 6.1 on 2026-08-29 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('teachers', '0008_teacher_account_number_teacher_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus where teacher was assigned during this period', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='schools.campus'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['campus', 'year', 'month', 'status'], name='payroll_campus_ym_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['teacher', 'year', 'month'], name='payroll_teacher_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['status', 'year', 'month'], name='payroll_status_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['teacher', 'status', 'effective_date'], name='salstruct_teacher_sts_date_idx'),
        ),
    ]
