# Generated by Django 6.1 on 2026-08-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_confirmation_date_employee_employment_type_and_more'),
        ('payroll', '0002_salarycomponenttemplate_salarystructurecomponent_and_more'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='hr.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='payroll.salarystructure'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
