# Generated by Django 6.1 on 2026-08-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrecord_campus_and_more'),
        ('payroll', '0003_alter_payrollrecord_employee_and_more'),
    ]

    operations = [
    ]
