# Generated by Django 6.1 on 2026-09-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_merge_20260829_1001'),
        ('payroll', '0004_merge_20260829_1000'),
        ('schools', '0027_subjectoffering_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_teacher_ym_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarystructure',
            name='salstruct_teacher_sts_date_idx',
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus where employee was assigned during this period', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='schools.campus'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee', 'year', 'month'], name='payroll_employee_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', 'status', 'effective_date'], name='salstruct_emp_sts_date_idx'),
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='teacher',
        ),
    ]
