# Generated by Django 6.1 on 2026-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentreversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Checkout Session ID for online payments.', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('card', 'Card'), ('stripe', 'Stripe (Online)'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
