# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_concession_journalentry_expense_journalline_and_more'),
        ('schools', '0008_add_institution_to_all_models'),
        ('students', '0009_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='schools.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='schools.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='schools.school'),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reversals', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='feecategory',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_fee_category_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('institution', 'invoice_number'), name='unique_invoice_number_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('institution', 'receipt_number'), name='unique_receipt_number_per_institution'),
        ),
    ]
