# Generated by Django 6.1 on 2026-08-29 03:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_account_deleted_at_account_deleted_by_and_more'),
        ('schools', '0019_subjectoffering_is_compulsory_and_more'),
        ('students', '0011_academichistory_campustransfer_inquiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Override amount. Overrides the fee structure amount for this student.', max_digits=12)),
                ('reason', models.TextField(blank=True, help_text='Reason for the override (e.g., scholarship, sibling discount).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student', 'fee_structure'],
            },
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['campus', 'class_obj', 'section', 'category']},
        ),
        migrations.RemoveConstraint(
            model_name='feestructure',
            name='unique_fee_structure',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='installment_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of installments. 1 = single payment.'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='installment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Per Term'), ('quarterly', 'Quarterly')], default='monthly', help_text='Frequency of installments when count > 1.', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict to a specific section. Null means all sections.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='schools.section'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of installments this invoice is split into.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('termly', 'Per Term'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total late fees applied to this invoice.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_applied',
            field=models.BooleanField(default=False, help_text='Whether a late fee has been applied to this invoice.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_date',
            field=models.DateField(blank=True, help_text='Date when late fee was last applied.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='next_installment_due',
            field=models.DateField(blank=True, help_text='Due date of the next pending installment.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1, help_text='Which installment this payment is for (1-based).'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('academic_year', 'campus', 'class_obj', 'section', 'category'), name='unique_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_session_id', ''), _negated=True), fields=('stripe_session_id',), name='unique_stripe_session_id'),
        ),
        migrations.AddField(
            model_name='studentfeeoverride',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfeeoverride',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_overrides', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfeeoverride',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_overrides', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentfeeoverride',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_overrides', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeoverride',
            constraint=models.UniqueConstraint(fields=('student', 'fee_structure'), name='unique_student_fee_override'),
        ),
    ]
