# Generated by Django 6.1 on 2026-09-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_bankaccount_bankreconciliation_budget_budgetline_and_more'),
        ('schools', '0027_subjectoffering_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='concession',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='fine',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='studentfeeoverride',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_overrides', to='schools.campus'),
        ),
    ]
