# Generated by Django 6.1 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


def backfill_student_fee_override_institution(apps, schema_editor):
    """Backfill null institution on existing StudentFeeOverride rows.

    Prefer the student's institution; fall back to the fee structure's
    academic year school (always resolvable because AcademicYear.school
    is non-nullable).
    """
    StudentFeeOverride = apps.get_model("finance", "StudentFeeOverride")

    rows = (
        StudentFeeOverride.objects
        .filter(institution__isnull=True)
        .select_related("student", "fee_structure__academic_year__school")
    )

    for override in rows:
        institution = (
            getattr(override.student, "institution_id", None)
            or getattr(
                override.fee_structure.academic_year.school,
                "id",
                None,
            )
        )

        if institution is not None:
            StudentFeeOverride.objects.filter(pk=override.pk).update(
                institution_id=institution
            )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_adjustment_campus_concession_campus_fine_campus_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_student_fee_override_institution,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="studentfeeoverride",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fee_overrides",
                to="schools.school",
            ),
        ),
    ]