# Generated by Django 6.1 on 2026-09-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_studentfeeoverride_institution'),
        ('schools', '0028_schoolsettings_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'year', 'prefix'), name='unique_number_sequence_per_institution_year_prefix')],
            },
        ),
    ]
