import {
  LayoutDashboard,
  Users,
  GraduationCap,
  ClipboardCheck,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  FileText,
  BarChart3,
  Star,
  Clock,
  Download,
  Filter,
  Settings,
  Plus,
  Grid,
  List,
  ChevronRight,
  ExternalLink,
  Printer,
  Mail,
  Building,
  Briefcase,
  UserX,
  CheckCircle,
  Truck,
  MapPin,
  ShoppingCart,
  ArrowRightLeft,
  ArrowRight,
  ArrowLeft,
  AlertTriangle,
  Database,
  Badge,
} from "lucide-react";

const REPORT_CATEGORIES = [
  {
    category: "Dashboard",
    slug: "dashboard",
    icon: LayoutDashboard,
    description: "Executive overview and key metrics",
    reports: [
      { key: "dashboard", title: "Executive Dashboard", description: "Real-time overview of key metrics", icon: LayoutDashboard },
    ],
  },
  {
    category: "Students & Admissions",
    slug: "students-admissions",
    icon: Users,
    description: "Student master data, admissions, and lifecycle reports",
    reports: [
      { key: "student-master", title: "Student Master Report", description: "Complete student directory with all details", icon: Users },
      { key: "student-list", title: "Student List Reports", description: "Active, inactive, graduated, withdrawn, new admissions", icon: Users },
      { key: "student-profile", title: "Student Profile", description: "Detailed profile with academics, attendance, fees, discipline", icon: FileText },
      { key: "student-statistics", title: "Student Statistics", description: "Age distribution, gender, campus, admission trends", icon: BarChart3 },
      { key: "admissions", title: "Admissions Register", description: "Applications, pending, approved, rejected, transfers", icon: GraduationCap },
    ],
  },
  {
    category: "Attendance",
    slug: "attendance",
    icon: ClipboardCheck,
    description: "Daily, monthly, student, class attendance and analytics",
    reports: [
      { key: "attendance-daily", title: "Daily Attendance", description: "Daily attendance by class/section", icon: ClipboardCheck },
      { key: "attendance-monthly", title: "Monthly Attendance", description: "Monthly attendance summaries by class", icon: CalendarDays },
      { key: "attendance-student", title: "Student Attendance", description: "Individual student attendance history", icon: FileText },
      { key: "attendance-class", title: "Class Attendance", description: "Class/section attendance summaries", icon: Users },
      { key: "attendance-analytics", title: "Attendance Analytics", description: "Campus/class comparison, thresholds, perfect attendance", icon: BarChart3 },
      { key: "attendance-chronic", title: "Chronic Absentees", description: "Students below attendance threshold", icon: Siren },
      { key: "attendance-subject", title: "Subject Attendance", description: "Subject-wise attendance (if timetable integrated)", icon: BookOpen },
    ],
  },
  {
    category: "Academics & Examinations",
    slug: "academics-exams",
    icon: GraduationCap,
    description: "Exam schedules, marks, results, report cards, rankings",
    reports: [
      { key: "exam-schedule", title: "Exam Schedule", description: "Upcoming and past exam schedules", icon: CalendarDays },
      { key: "exam-marks", title: "Exam Marks", description: "Subject-wise marks for an exam", icon: Table2 },
      { key: "exam-subject-performance", title: "Subject Performance", description: "Per-subject averages, pass rates, highest/lowest", icon: BarChart3 },
      { key: "exam-class-marks", title: "Class Marks", description: "Class-wise performance for an exam", icon: Users },
      { key: "exam-student-result", title: "Student Result", description: "Detailed student result with subjects, grades, position", icon: FileText },
      { key: "exam-analytics", title: "Result Analytics", description: "Grade distribution, top/bottom performers, comparisons", icon: BarChart3 },
      { key: "exam-ranking", title: "Student Ranking", description: "Rankings within class/campus", icon: Trophy },
      { key: "exam-report-card", title: "Report Card Generator", description: "Professional report cards with branding, bulk PDF", icon: FileText },
    ],
  },
  {
    category: "Fees & Finance",
    slug: "fees-finance",
    icon: Wallet,
    description: "Fee collection, status, analytics, finance reports",
    reports: [
      { key: "fee-collection", title: "Fee Collection", description: "Daily/weekly/monthly collection by campus, class, method", icon: Wallet },
      { key: "fee-status", title: "Fee Status", description: "Paid, unpaid, partial, overdue, outstanding, upcoming, waived", icon: ClipboardCheck },
      { key: "fee-analytics", title: "Fee Analytics", description: "Trends, campus/class/fee-type/payment-method comparisons", icon: BarChart3 },
      { key: "fee-defaulters", title: "Fee Defaulters", description: "Students with outstanding balances", icon: Siren },
      { key: "finance", title: "Finance Reports", description: "Income, expense, P&L, cash flow, account ledger", icon: BookOpen },
    ],
  },
  {
    category: "HR & Payroll",
    slug: "hr-payroll",
    icon: Users,
    description: "Employee master, attendance, leave, payroll, salary slips",
    reports: [
      { key: "hr-employees", title: "Employee Master", description: "HR employee directory with department, designation, campus", icon: Users },
      { key: "hr-attendance", title: "HR Attendance", description: "Staff attendance records with check-in/out", icon: ClipboardCheck },
      { key: "hr-leave", title: "HR Leave", description: "Leave requests by type, status, employee", icon: CalendarDays },
      { key: "payroll-monthly", title: "Monthly Payroll", description: "Payroll records for a specific period", icon: Wallet },
      { key: "payroll-salary-slip", title: "Salary Slip", description: "Detailed salary slip with allowances/deductions", icon: FileText },
      { key: "payroll-summary", title: "Payroll Summary", description: "Payroll totals by period and campus", icon: BarChart3 },
      { key: "payroll-allowances", title: "Allowances Report", description: "Allowance breakdown by type", icon: Wallet },
      { key: "payroll-deductions", title: "Deductions Report", description: "Deduction breakdown by type", icon: Wallet },
      { key: "payroll-net-salary", title: "Net Salary", description: "Net salary by campus/department", icon: Wallet },
      { key: "payroll-paid", title: "Paid Salaries", description: "Employees with paid status", icon: Trophy },
      { key: "payroll-pending", title: "Pending Salaries", description: "Employees with pending payroll", icon: Clock },
    ],
  },
  {
    category: "Staff & Teachers",
    slug: "staff-teachers",
    icon: Users,
    description: "Staff/teacher master, attendance, leave, workload, assignments",
    reports: [
      { key: "staff-master", title: "Staff Master", description: "Complete staff directory with designations, departments", icon: Users },
      { key: "teacher-master", title: "Teacher Master", description: "Teachers with qualifications, subjects, assignments", icon: GraduationCap },
      { key: "staff-attendance", title: "Staff Attendance", description: "Daily attendance records for staff", icon: ClipboardCheck },
      { key: "teacher-attendance", title: "Teacher Attendance", description: "Daily attendance records for teachers", icon: GraduationCap },
      { key: "staff-leave", title: "Staff Leave", description: "Staff leave requests by type and status", icon: CalendarDays },
      { key: "teacher-leave", title: "Teacher Leave", description: "Teacher leave requests by type and status", icon: CalendarDays },
      { key: "teacher-workload", title: "Teacher Workload", description: "Subjects, classes, sections assigned per teacher", icon: Briefcase },
      { key: "staff-department", title: "Department Report", description: "Staff count by department and campus", icon: Building },
      { key: "staff-designation", title: "Designation Report", description: "Staff count by designation and campus", icon: Briefcase },
      { key: "staff-joining", title: "Staff Joining", description: "New hires by period", icon: CalendarDays },
      { key: "staff-resignation", title: "Staff Resignation", description: "Resignations/terminations by period", icon: UserX },
    ],
  },
  {
    category: "Academic Operations",
    slug: "academic-ops",
    icon: BookOpen,
    description: "Class strength, subject allocation, timetables, promotions",
    reports: [
      { key: "class-strength", title: "Class Strength", description: "Student count by class/section with gender breakdown", icon: Users },
      { key: "section-strength", title: "Section Strength", description: "Detailed section-wise student counts", icon: Users },
      { key: "class-student-list", title: "Class Student List", description: "Roll-numbered student lists by class/section", icon: ClipboardCheck },
      { key: "gender-distribution", title: "Gender Distribution", description: "Male/female distribution by campus/class", icon: BarChart3 },
      { key: "academic-performance", title: "Academic Performance", description: "Class-wise pass rates, averages for an exam", icon: Trophy },
      { key: "promotion", title: "Promotion Report", description: "Graduated/transferred students with from/to details", icon: GraduationCap },
      { key: "subject-list", title: "Subject List", description: "All subjects with codes, types, practical flags", icon: BookOpen },
      { key: "subject-allocation", title: "Subject Allocation", description: "Subject-teacher-class assignments", icon: Users },
      { key: "subject-performance", title: "Subject Performance", description: "Cross-class subject averages, pass rates", icon: BarChart3 },
      { key: "teacher-subjects", title: "Teacher Subject Allocation", description: "Subjects and classes assigned per teacher", icon: GraduationCap },
      { key: "timetable-student", title: "Student Timetable", description: "Weekly timetable for a student", icon: CalendarDays },
      { key: "timetable-class", title: "Class Timetable", description: "Weekly timetable for a class/section", icon: CalendarDays },
      { key: "timetable-teacher", title: "Teacher Timetable", description: "Weekly timetable for a teacher", icon: CalendarDays },
      { key: "timetable-room", title: "Room Timetable", description: "Weekly timetable for a room", icon: CalendarDays },
      { key: "timetable-free-periods", title: "Free Periods", description: "Teacher free period analysis", icon: Clock },
    ],
  },
  {
    category: "Parents & Guardians",
    slug: "parents",
    icon: Users,
    description: "Parent master, relationships, contacts, fee/attendance/academic summaries",
    reports: [
      { key: "parent-master", title: "Parent Master", description: "Guardian directory with contact details", icon: Users },
      { key: "parent-relationship", title: "Parent-Student Relationships", description: "Primary/emergency/pickup contacts per student", icon: Users },
      { key: "parent-contact", title: "Parent Contact Report", description: "Phone/email/address with missing contact flags", icon: Mail },
      { key: "parent-students", title: "Parent-wise Students", description: "Students grouped by parent with class details", icon: Users },
      { key: "parent-outstanding-fees", title: "Outstanding Fees by Parent", description: "Total dues per guardian across all children", icon: Wallet },
      { key: "parent-attendance", title: "Attendance Summary by Parent", description: "Children's attendance rates grouped by parent", icon: ClipboardCheck },
      { key: "parent-academic", title: "Academic Summary by Parent", description: "Children's exam performance grouped by parent", icon: Trophy },
    ],
  },
  {
    category: "Library",
    slug: "library",
    icon: BookOpen,
    description: "Book inventory, issues, returns, fines, borrowing history",
    reports: [
      { key: "library-inventory", title: "Book Inventory", description: "Total books, copies, available/issued by category", icon: BookOpen },
      { key: "library-available", title: "Available Books", description: "Currently available copies with locations", icon: CheckCircle },
      { key: "library-issued", title: "Issued Books", description: "Currently issued/overdue books with borrower details", icon: BookOpen },
      { key: "library-returned", title: "Returned Books", description: "Returned books with late return analysis", icon: BookOpen },
      { key: "library-overdue", title: "Overdue Books", description: "Overdue books with days overdue and fines", icon: Siren },
      { key: "library-fines", title: "Library Fines", description: "Fines outstanding/paid with borrower details", icon: Wallet },
      { key: "library-activity", title: "Library Activity Summary", description: "Total issues, returns, overdue, fines, most borrowed", icon: BarChart3 },
      { key: "library-most-borrowed", title: "Most Borrowed Books", description: "Top borrowed titles with issue counts", icon: Trophy },
      { key: "library-student-history", title: "Student Borrowing History", description: "Complete issue/return history for a student", icon: FileText },
      { key: "library-teacher-history", title: "Teacher Borrowing History", description: "Complete issue/return history for a teacher", icon: FileText },
    ],
  },
  {
    category: "Transport",
    slug: "transport",
    icon: Bus,
    description: "Student assignments, routes, vehicles, drivers, fees",
    reports: [
      { key: "transport-students", title: "Student Transport List", description: "Students with route, vehicle, driver, pickup/drop points", icon: Users },
      { key: "transport-routes", title: "Route Report", description: "Route details with vehicle, driver, stops, utilization", icon: Bus },
      { key: "transport-vehicles", title: "Vehicle Report", description: "Vehicles with capacity, status, routes, insurance/fitness", icon: Truck },
      { key: "transport-drivers", title: "Driver Report", description: "Drivers with license, vehicle, routes, assigned students", icon: Users },
      { key: "transport-pickup-dropoff", title: "Pickup/Drop-off Points", description: "All pickup and drop points with times", icon: MapPin },
      { key: "transport-students-by-route", title: "Students by Route", description: "Student lists grouped by route", icon: Users },
      { key: "transport-students-by-vehicle", title: "Students by Vehicle", description: "Student lists grouped by vehicle", icon: Truck },
      { key: "transport-fees", title: "Transport Fees", description: "Monthly transport fees by student/route", icon: Wallet },
      { key: "transport-vehicle-capacity", title: "Vehicle Capacity", description: "Capacity utilization per vehicle", icon: BarChart3 },
      { key: "transport-route-occupancy", title: "Route Occupancy", description: "Route capacity vs assigned students, overloaded routes", icon: BarChart3 },
    ],
  },
  {
    category: "Inventory & Assets",
    slug: "inventory",
    icon: Package,
    description: "Asset master, stock levels, movements, purchases, valuation",
    reports: [
      { key: "inventory-master", title: "Inventory Master", description: "All assets with category, campus, quantity, value", icon: Package },
      { key: "inventory-stock", title: "Current Stock", description: "Available stock by item/category/campus", icon: Package },
      { key: "inventory-low-stock", title: "Low Stock", description: "Items below reorder threshold", icon: Siren },
      { key: "inventory-out-of-stock", title: "Out of Stock", description: "Items with zero quantity", icon: X },
      { key: "inventory-movement", title: "Stock Movement", description: "Inward/outward/transfer movements by date range", icon: ArrowRightLeft },
      { key: "inventory-purchases", title: "Purchases", description: "Purchase orders with supplier, amount, status", icon: ShoppingCart },
      { key: "inventory-issues", title: "Issues", description: "Assets issued to staff/students with return tracking", icon: ArrowRight },
      { key: "inventory-returns", title: "Returns", description: "Asset returns with condition assessment", icon: ArrowLeft },
      { key: "inventory-damaged", title: "Damaged Items", description: "Assets marked damaged with value", icon: AlertTriangle },
      { key: "inventory-lost", title: "Lost Items", description: "Assets marked lost with value", icon: AlertTriangle },
      { key: "inventory-category", title: "Category Report", description: "Item counts and values by category", icon: BarChart3 },
      { key: "inventory-supplier", title: "Supplier Report", description: "Assets and purchase values by supplier", icon: Truck },
      { key: "inventory-valuation", title: "Inventory Valuation", description: "Total asset value by category and campus", icon: Wallet },
    ],
  },
  {
    category: "Discipline",
    slug: "discipline",
    icon: Siren,
    description: "Incidents, warnings, suspensions, student history",
    reports: [
      { key: "discipline-incidents", title: "Discipline Incidents", description: "All incidents with type, severity, action taken", icon: Siren },
      { key: "discipline-student", title: "Student Incidents", description: "Incidents grouped by student with counts", icon: Users },
      { key: "discipline-class", title: "Class Incidents", description: "Incident counts by class with type breakdown", icon: Users },
      { key: "discipline-campus", title: "Campus Incidents", description: "Incident counts and severity by campus", icon: MapPin },
      { key: "discipline-type", title: "Incident Type Breakdown", description: "Counts by incident type and severity", icon: BarChart3 },
      { key: "discipline-date-range", title: "Date Range Incidents", description: "Incidents within a specific date range", icon: CalendarDays },
      { key: "discipline-warnings", title: "Warnings", description: "All warning-level incidents", icon: AlertTriangle },
      { key: "discipline-suspensions", title: "Suspensions", description: "All suspension incidents with action taken", icon: UserX },
      { key: "discipline-repeat", title: "Repeat Offenders", description: "Students with multiple incidents", icon: Siren },
      { key: "discipline-history", title: "Disciplinary History", description: "Complete incident timeline for a student", icon: FileText },
    ],
  },
  {
    category: "Certificates & ID Cards",
    slug: "certificates",
    icon: FileText,
    description: "Generate certificates and ID cards with templates",
    reports: [
      { key: "certificate-bonafide", title: "Bonafide Certificate", description: "Proof of enrollment certificate", icon: FileText },
      { key: "certificate-character", title: "Character Certificate", description: "Good conduct certificate", icon: FileText },
      { key: "certificate-leaving", title: "Leaving Certificate", description: "School leaving certificate", icon: FileText },
      { key: "certificate-transfer", title: "Transfer Certificate", description: "Inter-school transfer certificate", icon: FileText },
      { key: "certificate-enrollment", title: "Enrollment Certificate", description: "Current enrollment verification", icon: FileText },
      { key: "certificate-fee-clearance", title: "Fee Clearance Certificate", description: "No dues certificate", icon: FileText },
      { key: "certificate-student-id", title: "Student ID Card", description: "Photo ID card with barcode", icon: Badge },
      { key: "certificate-staff-id", title: "Staff ID Card", description: "Staff photo ID card with barcode", icon: Badge },
      { key: "certificate-templates", title: "Certificate Templates", description: "Manage certificate templates", icon: Settings },
    ],
  },
  {
    category: "Campus Reports",
    slug: "campus",
    icon: Building,
    description: "Cross-campus comparison and individual campus dashboards",
    reports: [
      { key: "campus-students", title: "Campus Student Count", description: "Student totals with gender breakdown by campus", icon: Users },
      { key: "campus-attendance", title: "Campus Attendance", description: "Attendance rate comparison across campuses", icon: ClipboardCheck },
      { key: "campus-performance", title: "Campus Academic Performance", description: "Pass rates, averages, grade distribution by campus", icon: Trophy },
      { key: "campus-fees", title: "Campus Fee Collection", description: "Invoiced, collected, outstanding by campus", icon: Wallet },
      { key: "campus-outstanding", title: "Campus Outstanding Fees", description: "Outstanding fee totals by campus", icon: Siren },
      { key: "campus-staff", title: "Campus Staff Count", description: "Staff totals with teaching/admin breakdown", icon: Users },
      { key: "campus-admissions", title: "Campus Admissions", description: "Applications, accepted, pending by campus", icon: GraduationCap },
      { key: "campus-finance", title: "Campus Financial Summary", description: "Revenue, expenses, net by campus", icon: Wallet },
      { key: "campus-comparison", title: "Campus Comparison", description: "Side-by-side KPI comparison", icon: BarChart3 },
      { key: "campus-dashboard", title: "Campus Dashboard", description: "Single campus overview with all KPIs", icon: LayoutDashboard },
    ],
  },
  {
    category: "Report Builder",
    slug: "builder",
    icon: Plus,
    description: "Create custom reports from approved data sources",
    reports: [
      { key: "builder-data-sources", title: "Available Data Sources", description: "Browse approved data sources with fields and filters", icon: Database },
      { key: "builder-create", title: "Create Custom Report", description: "Select fields, add filters, grouping, sorting", icon: Plus },
      { key: "builder-saved", title: "My Saved Reports", description: "Manage and run saved custom reports", icon: Star },
      { key: "builder-templates", title: "Report Templates", description: "Manage PDF/print templates", icon: FileText },
    ],
  },
];

export { REPORT_CATEGORIES };

export interface ReportConfig {
  key: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ size?: number }>;
  category: string;
}

export interface ReportCategory {
  category: string;
  slug: string;
  icon: React.ComponentType<{ size?: number }>;
  description: string;
  reports: ReportConfig[];
}

export interface ReportData {
  [key: string]: any;
}

export interface ReportSummary {
  [key: string]: any;
}