import {
  LayoutDashboard,
  BarChart3,
  FileText,
  Search,
  Star,
  Clock,
  Download,
  Filter,
  Settings,
  Plus,
  Grid,
  List,
  ChevronRight,
  ExternalLink,
  Printer,
  Mail,
  Clock,
  Filter,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
  Users,
  GraduationCap,
  Wallet,
  BookOpen,
  Bus,
  Package,
  Wrench,
  CalendarDays,
  MessageSquare,
  Trophy,
  Table2,
  Siren,
  ClipboardCheck,
} from "lucide-react";
import { PageHeader, PanelHeader, StateArea, StatCard, Button, TabButton, Badge } from "./ui";
import { apiFetch } from "../api";
import { formatCurrency } from "./format";

const BASE = "/api/reports/";

const REPORT_CATEGORIES = [
  {
    category: "Dashboard",
    icon: LayoutDashboard,
    reports: [
      { key: "dashboard", title: "Executive Dashboard", icon: LayoutDashboard, description: "Real-time overview of key metrics" },
    ],
  },
  {
    category: "Students & Admissions",
    icon: Users,
    reports: [
      { key: "enrollment", title: "Enrollment Report", description: "Student enrollment by campus, class, section" },
      { key: "admissions", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "student-status", title: "Student Status", description: "Active, inactive, graduated, withdrawn" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "student-status", title: "Student Status", description: "Active, inactive, graduated, withdrawn" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transfers", title: "Transfers", description: "Transfer in/out records" },
      { key: "withdrawals", title: "Withdrawals", description: "Student withdrawal records" },
    ],
  },
  {
    category: "Attendance",
    icon: ClipboardCheck,
    reports: [
      { key: "attendance", title: "Daily Attendance", description: "Daily attendance by class/section" },
      { key: "attendance-monthly", title: "Monthly Attendance", description: "Monthly attendance summaries" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "student-attendance", title: "Student Attendance", description: "Individual student attendance history" },
      { key: "teacher-attendance", title: "Teacher Attendance", description: "Staff attendance records" },
    ],
  },
  {
    category: "Academics & Examinations",
    icon: GraduationCap,
    reports: [
      { key: "results", title: "Exam Results", description: "Exam-wise student results" },
      { key: "subjects", title: "Subject Performance", description: "Per-subject performance analysis" },
      { key: "class-performance", title: "Class Performance", description: "Class-wise academic performance" },
      { key: "student-progress", title: "Student Progress", description: "Student performance trends" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "gradebook", title: "Gradebook", description: "Interactive gradebook with exams" },
      { key: "report-cards", title: "Report Cards", description: "Generate and print report cards" },
      { key: "gradebook", title: "Gradebook", description: "Interactive gradebook with exams" },
    ],
  },
  {
    category: "Fees & Finance",
    icon: Wallet,
    reports: [
      { key: "fees", title: "Fee Collection", description: "Fee collection by campus/class" },
      { key: "fees", title: "Fee Collection", description: "Fee collection summary by campus" },
      { key: "fee-defaulters", title: "Fee Defaulters", description: "Students with outstanding balances" },
      { key: "fee-categories", title: "Fee Categories", description: "Invoiced amounts by fee category" },
      { key: "discounts", title: "Discounts & Concessions", description: "Discounts and concessions given" },
      { key: "payments", title: "Payments", description: "Payment method breakdown" },
      { key: "collection-trend", title: "Collection Trend", description: "Monthly collection trends" },
      { key: "fee-categories", title: "Fee Categories", description: "Invoiced amounts by fee category" },
      { key: "fee-defaulters", title: "Fee Defaulters", description: "Students with outstanding balances" },
      { key: "discounts", title: "Discounts & Concessions", description: "Discounts and concessions given" },
      { key: "payments", title: "Payments", description: "Payment method breakdown" },
    ],
  },
  {
    category: "Reports & Analytics",
    icon: BarChart3,
    reports: [
      { key: "collection-trend", title: "Collection Trend", description: "Monthly fee collection trends" },
      { key: "class-performance", title: "Class Performance", description: "Class-wise academic performance" },
      { key: "student-progress", title: "Student Progress", description: "Student performance trends" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "student-progress", title: "Student Progress", description: "Student performance trends" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
    ],
  },
  {
    category: "Staff & HR",
    icon: Users,
    reports: [
      { key: "staff", title: "Staff Report", description: "Staff summary by campus/designation" },
      { key: "teacher-workload", title: "Teacher Workload", description: "Teacher assignments and workload" },
      { key: "payroll-summary", title: "Payroll Summary", description: "Payroll summary by period" },
      { key: "payroll-summary", title: "Payroll Summary", description: "Payroll summary by period" },
      { key: "staff", title: "Staff Report", description: "Staff summary by campus/designation" },
      { key: "teacher-workload", title: "Teacher Workload", description: "Teacher assignments and workload" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Communication",
    icon: MessageSquare,
    reports: [
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
  {
    category: "Admissions & Certificates",
    icon: FileText,
    reports: [
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "admissions-register", title: "Admissions Register", description: "Applications, pending, approved, rejected" },
      { key: "transcripts", title: "Transcripts", description: "Academic transcripts" },
      { key: "leaving-certificates", title: "Leaving Certificates", description: "School leaving certificates" },
      { key: "transfer-certificates", title: "Transfer Certificates", description: "Transfer certificates issued" },
      { key: "character-certificates", title: "Character Certificates", description: "Character certificates issued" },
      { key: "bonafide-certificates", title: "Bonafide Certificates", description: "Bonafide certificates issued" },
    ],
  },
  {
    category: "Operations",
    icon: Settings,
    reports: [
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "library", title: "Library Overview", description: "Books, issues, overdue, fines" },
      { key: "route-utilization", title: "Route Utilization", description: "Vehicle route utilization" },
      { key: "inventory-value", title: "Inventory Value", description: "Asset inventory valuation" },
      { key: "maintenance-due", title: "Maintenance Due", description: "Assets due for maintenance" },
      { key: "event-participation", title: "Event Participation", description: "Event attendance tracking" },
      { key: "sms-usage", title: "SMS Usage", description: "SMS delivery statistics" },
      { key: "top-performers", title: "Top Performers", description: "Top performing students" },
      { key: "chronic-absentee", title: "Chronic Absentees", description: "Students below attendance threshold" },
      { key: "at-risk", title: "At-Risk Students", description: "Students flagged as at-risk" },
    ],
  },
];

export { REPORTS };

// --- Types ---
export interface ReportConfig {
  key: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ size?: number }>;
  category: string;
}

export interface ReportCategory {
  category: string;
  icon: React.ComponentType<{ size?: number }>;
  reports: ReportConfig[];
}

export interface ReportConfig {
  key: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ size?: number }>;
  category: string;
}

export interface ReportData {
  [key: string]: any;
}

export interface ReportSummary {
  [key: string]: any;
}

export interface ReportData {
  [key: string]: any;
}