# Generated by Django 6.1 on 2026-08-28 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text="Stable key used by the engine, e.g. 'hr.leave.request'.", max_length=100)),
                ('object_type', models.CharField(db_index=True, help_text="Dot path of the business object, e.g. 'hr.leaverequest'.", max_length=120)),
                ('states', models.JSONField(default=list, help_text="Valid states, e.g. ['draft', 'pending_approval', 'approved', 'rejected'].")),
                ('initial_state', models.CharField(max_length=50)),
                ('approval_steps', models.JSONField(blank=True, default=list, help_text="Ordered role slugs. Each step must approve in sequence before 'approve' moves the object to its target state.")),
                ('transitions', models.JSONField(blank=True, default=dict, help_text="Map action -> {'from': [...], 'to': ..., 'roles': [...]}. 'approve'/'reject' walk the approval_steps queue; every other action is a plain state hop.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow definition',
                'ordering': ('object_type', 'slug'),
                'constraints': [models.UniqueConstraint(fields=('object_type', 'slug'), name='uniq_workflow_definition_object_slug')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('current_state', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='schools.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='schools.school')),
            ],
            options={
                'verbose_name': 'Workflow instance',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow.workflowinstance')),
            ],
            options={
                'verbose_name': 'Workflow approval',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_state', models.CharField(blank=True, default='', max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowinstance')),
            ],
            options={
                'verbose_name': 'Workflow transition',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['object_type', 'object_id'], name='workflow_wo_object__0a061b_idx'),
        ),
    ]
