# Generated by Django 6.1 on 2026-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdefinition',
            name='slug',
            field=models.CharField(db_index=True, help_text="Stable key used by the engine and API, e.g. 'hr.leave.request'.", max_length=100),
        ),
    ]
