# Generated by Django 6.1 on 2026-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='Store absence separately from a score of zero.'),
        ),
    ]
