# Generated by Django 6.1 on 2026-08-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentresult_is_absent'),
        ('students', '0004_guardian_user_studentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximum_marks', models.PositiveIntegerField(default=50)),
                ('passing_marks', models.PositiveIntegerField(default=20)),
                ('is_absent', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=3)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_results', to='exams.exam')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_results', to='exams.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_exam_results', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'student', 'exam_subject'), name='unique_student_exam_subject_practical')],
            },
        ),
    ]
