# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('exams', '0003_practicalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='exams',
                to='schools.term',
            ),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, help_text='Room, hall or location for the exam.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam')),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='exams.examsubject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='schools.section')),
            ],
            options={
                'ordering': ['date', 'start_time', 'section__name'],
                'indexes': [
                    models.Index(fields=['exam', 'date', 'start_time'], name='examsched_exam_date_idx'),
                    models.Index(fields=['section', 'date', 'start_time'], name='examsched_sec_date_idx'),
                    models.Index(fields=['date', 'room'], name='examsched_date_room_idx'),
                ],
            },
        ),
    ]
