# Generated by Django 6.1 on 2026-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examschedule_and_more'),
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('students', '0010_progressionrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['campus', 'academic_year', 'status'], name='exam_campus_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['class_obj', 'exam_type', 'status'], name='exam_class_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date', 'end_date'], name='exam_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['exam', 'student'], name='result_exam_student_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['exam_subject', 'is_pass'], name='result_subject_pass_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['grade', 'is_pass'], name='result_grade_pass_idx'),
        ),
    ]
