# Generated by Django 6.1 on 2026-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_exam_campus_year_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevents editing of this result record.'),
        ),
    ]
