# Generated by Django 6.1 on 2026-08-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_exam_campus_year_status_idx_and_more'),
        ('schools', '0020_alter_subject_code'),
        ('students', '0011_academichistory_campustransfer_inquiry_and_more'),
        ('teachers', '0009_teacher_deleted_at_teacher_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='invigilator',
            field=models.ForeignKey(blank=True, help_text='Teacher supervising this exam slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_invigilations', to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='ExamSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('room', models.CharField(blank=True, help_text='Room or hall assigned for the student.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='exams.exam')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_seating', to='schools.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seating', to='students.student')),
            ],
            options={
                'ordering': ['section', 'seat_number', 'student__first_name'],
                'indexes': [models.Index(fields=['exam', 'section', 'seat_number'], name='seating_exam_section_seat_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_seat_per_exam'), models.UniqueConstraint(fields=('exam', 'section', 'seat_number'), name='unique_seat_number_per_section_exam')],
            },
        ),
    ]
