# Generated by Django 6.1 on 2026-08-31 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examschedule_invigilator_examseating'),
        ('exams', '0006_studentresult_is_locked'),
    ]

    operations = [
    ]
