# Generated by Django 6.1 on 2026-09-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_merge_20260831_0652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_grade', models.CharField(max_length=3)),
                ('original_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_is_pass', models.BooleanField()),
                ('requested_grade', models.CharField(max_length=3)),
                ('requested_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('requested_is_pass', models.BooleanField()),
                ('reason', models.TextField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_amendments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_amendments', to=settings.AUTH_USER_MODEL)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='exams.studentresult')),
            ],
            options={
                'verbose_name': 'Grade Amendment',
                'verbose_name_plural': 'Grade Amendments',
                'ordering': ['-requested_at'],
            },
        ),
    ]
