# Generated by Django 6.1 on 2026-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_institutionmembership_roleassignment_staffprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/staff/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/users/'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Super Admin'), ('admin', 'Institution Admin'), ('principal', 'Principal'), ('academic', 'Academic Administrator'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff Member')], max_length=30),
        ),
    ]
