# Generated by Django 6.1 on 2026-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Super Admin'), ('admin', 'Institution Admin'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('campus_admin', 'Campus Administrator'), ('academic', 'Academic Administrator'), ('accountant', 'Accountant'), ('hr', 'HR / Staff Officer'), ('receptionist', 'Receptionist'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('student', 'Student'), ('staff', 'Staff Member')], max_length=30),
        ),
    ]
