# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffprofile_membership_primary_campus'),
        ('schools', '0008_add_institution_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='schools.school'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to='schools.school'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(fields=('institution', 'employee_number'), name='unique_staff_employee_number_per_institution'),
        ),
    ]
