# Generated by Django 6.1 on 2026-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_populate_institution_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
