# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


def migrate_campus_char_to_fk(apps, schema_editor):
    """Migrate campus CharField data to primary_campus FK where possible."""
    StaffProfile = apps.get_model('accounts', 'StaffProfile')
    Campus = apps.get_model('schools', 'Campus')
    
    for staff in StaffProfile.objects.exclude(campus='').exclude(campus__isnull=True):
        # Try to find matching campus by name within the staff's institution
        if staff.institution_id:
            campus = Campus.objects.filter(
                school_id=staff.institution_id,
                name__iexact=staff.campus
            ).first()
            if campus:
                staff.primary_campus = campus
                staff.save(update_fields=['primary_campus'])


def reverse_migrate(apps, schema_editor):
    """No-op reverse - we don't want to repopulate the CharField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20260829_1001'),
    ]

    operations = [
        # Data migration to sync CharField to FK where possible
        migrations.RunPython(
            migrate_campus_char_to_fk,
            reverse_migrate,
        ),
        # Remove the duplicate campus CharField
        migrations.RemoveField(
            model_name='staffprofile',
            name='campus',
        ),
    ]