# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('accounts', '0010_user_twofa_enabled_user_twofa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffattendancecorrection_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'On Leave')], max_length=20)),
                ('to_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'On Leave')], max_length=20)),
                ('from_check_in', models.TimeField(blank=True, null=True)),
                ('to_check_in', models.TimeField(blank=True, null=True)),
                ('from_check_out', models.TimeField(blank=True, null=True)),
                ('to_check_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='accounts.staffattendance')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_corrections_made', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_corrections', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['-corrected_at'],
                'indexes': [
                    models.Index(fields=['attendance', '-corrected_at'], name='staff_att_corr_att_idx'),
                    models.Index(fields=['staff', 'corrected_by'], name='staff_att_corr_staff_idx'),
                ],
            },
        ),
    ]
