# Generated by Django 6.1 on 2026-08-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_roleassignment_role'),
        ('accounts', '0012_staffattendance_deleted_at_and_more'),
    ]

    operations = [
    ]
