# Generated by Django 6.1 on 2026-08-30 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_role_choices'),
        ('schools', '0020_alter_subject_code'),
        ('students', '0011_academichistory_campustransfer_inquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the transfer request.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_transfers_from', to='schools.campus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
                ('to_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_transfers_to', to='schools.campus')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='accounts_st_student_84c999_idx'), models.Index(fields=['status', 'requested_at'], name='accounts_st_status_2ae235_idx')],
            },
        ),
    ]
