# Generated by Django 6.1 on 2026-09-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_staffprofile_campus_charfield'),
        ('accounts', '0017_studenttransfer'),
    ]

    operations = [
    ]