# Generated by Django 6.1 on 2026-09-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_accounts_leaves'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0026_remove_subjectoffering_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Primary institution for this user. Null for super_admin users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('print', 'Print'), ('manage', 'Manage'), ('publish', 'Publish'), ('process', 'Process'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('refund', 'Refund'), ('return', 'Return'), ('overdue', 'Overdue'), ('adjust', 'Adjust'), ('grade', 'Grade'), ('send', 'Send'), ('backup', 'Backup'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username unique per institution. Super_admin users may have null institution.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('institution', 'username'), name='unique_username_per_institution'),
        ),
    ]
