# Generated by Django 6.1 on 2026-09-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_demote_duplicate_active_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.staffprofile'),
        ),
    ]
