# Generated by Django 6.1 on 2026-09-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_email_verified_and_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendancecorrection',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.staffprofile'),
        ),
    ]
