# Generated by Django 6.1 on 2026-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_seed_permissions_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('print', 'Print'), ('manage', 'Manage'), ('publish', 'Publish'), ('process', 'Process'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('refund', 'Refund'), ('return', 'Return'), ('overdue', 'Overdue'), ('adjust', 'Adjust'), ('grade', 'Grade'), ('send', 'Send'), ('backup', 'Backup'), ('maintenance', 'Maintenance'), ('ask', 'Ask'), ('search', 'Search'), ('anomaly', 'Anomaly'), ('communicate', 'Communicate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('student', 'Student Management'), ('teacher', 'Teacher Management'), ('staff', 'Staff Management'), ('admission', 'Admissions'), ('attendance', 'Attendance'), ('exam', 'Examinations'), ('finance', 'Finance & Fees'), ('payroll', 'Payroll'), ('hr', 'Human Resources'), ('library', 'Library'), ('transport', 'Transport'), ('inventory', 'Inventory'), ('hostel', 'Hostel'), ('lms', 'Learning Management'), ('communication', 'Communication'), ('settings', 'Settings'), ('report', 'Reports'), ('user', 'User Management'), ('role', 'Role Management'), ('permission', 'Permission Management'), ('system', 'System Administration'), ('insight', 'AI & Insights')], max_length=30),
        ),
    ]
