# Generated by Django 6.1 on 2026-09-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_seed_ai_permissions'),
        ('schools', '0030_campus_campus_school_status_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_role_per_membership',
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus-level scope for campus-level roles (principal, vice_principal, campus_admin). Null for school-level roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='schools.campus'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Super Admin'), ('admin', 'Institution Admin'), ('org_admin', 'Organization Administrator'), ('head_office', 'Head Office'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('campus_admin', 'Campus Administrator'), ('academic', 'Academic Administrator'), ('counsellor', 'Counsellor / Student Counselor'), ('accountant', 'Accountant'), ('hr', 'HR / Staff Officer'), ('receptionist', 'Receptionist'), ('administrative_officer', 'Administrative Officer'), ('librarian', 'Librarian'), ('guard', 'Security Guard'), ('nurse', 'Nurse / Medical Officer'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('student', 'Student'), ('staff', 'Staff Member')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Super Admin'), ('admin', 'Institution Admin'), ('org_admin', 'Organization Administrator'), ('head_office', 'Head Office'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('campus_admin', 'Campus Administrator'), ('academic', 'Academic Administrator'), ('counsellor', 'Counsellor / Student Counselor'), ('accountant', 'Accountant'), ('hr', 'HR / Staff Officer'), ('receptionist', 'Receptionist'), ('administrative_officer', 'Administrative Officer'), ('librarian', 'Librarian'), ('guard', 'Security Guard'), ('nurse', 'Nurse / Medical Officer'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('student', 'Student'), ('staff', 'Staff Member')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('membership', 'role'), name='unique_role_per_membership'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('membership', 'role', 'campus'), name='unique_role_per_membership_campus'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False), ('role', 'principal')), fields=('campus', 'role'), name='unique_principal_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False), ('role', 'vice_principal')), fields=('campus', 'role'), name='unique_vice_principal_per_campus'),
        ),
    ]
