# Generated by Django 6.1 on 2026-08-25 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_merge_schools_leaves'),
        ('students', '0009_add_institution_to_all_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('batch_year', models.PositiveIntegerField(help_text='Year of graduation / leaving.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active_member', models.BooleanField(default=True, help_text='Willing to be contacted for alumni events.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='schools.campus')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='schools.school')),
                ('student', models.OneToOneField(blank=True, help_text='Linked when the record was converted from a withdrawn/graduated student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_profile', to='students.student')),
            ],
            options={
                'ordering': ['-batch_year', 'full_name'],
            },
        ),
    ]
