"""Lazy-loaded views for the reports app to avoid circular imports during app loading."""

import sys
from importlib import import_module as _import_module
from types import ModuleType
from typing import Any

# Mapping of view names to their module paths
_VIEW_MODULES = {
    "ReportsRootView": "extended_views",
    "ChronicAbsenteeReportView": "extended_views",
    "CollectionTrendReportView": "extended_views",
    "DiscountsReportView": "extended_views",
    "EventParticipationReportView": "extended_views",
    "InventoryValueReportView": "extended_views",
    "LibraryOverviewReportView": "extended_views",
    "MaintenanceDueReportView": "extended_views",
    "PayrollSummaryReportView": "extended_views",
    "RouteUtilizationReportView": "extended_views",
    "SmsUsageReportView": "extended_views",
    "TopPerformersReportView": "extended_views",
    "DataBackupView": "export_views",
    "DataExportListView": "export_views",
    "DataExportView": "export_views",
    "PDFExportView": "pdf_views",
    "PrintView": "pdf_views",
    "ReportTemplatePreviewView": "pdf_views",
    "WeeklyReportEmailCronView": "cron_views",
    "AtRiskReportView": "at_risk_views",
    "ImportCommitView": "import_views",
    "ImportPreviewView": "import_views",
    "ImportTemplateView": "import_views",
    "SystemHealthView": "health_views",
    "StudentMasterReportView": "student_views",
    "StudentListReportView": "student_views",
    "AdmissionReportView": "student_views",
    "StudentProfileReportView": "student_views",
    "StudentStatisticsReportView": "student_views",
    "DailyAttendanceReportView": "attendance_views",
    "MonthlyAttendanceReportView": "attendance_views",
    "StudentAttendanceReportView": "attendance_views",
    "ClassAttendanceReportView": "attendance_views",
    "AttendanceAnalyticsReportView": "attendance_views",
    "ChronicAbsenteeReportView": "attendance_views",
    "SubjectAttendanceReportView": "attendance_views",
    "ExamScheduleReportView": "exam_views",
    "ExamMarksReportView": "exam_views",
    "SubjectPerformanceReportView": "exam_views",
    "ClassMarksReportView": "exam_views",
    "StudentResultReportView": "exam_views",
    "ResultAnalyticsReportView": "exam_views",
    "StudentRankingReportView": "exam_views",
    "ReportCardGeneratorView": "exam_views",
    "FeeCollectionReportView": "fee_views",
    "FeeStatusReportView": "fee_views",
    "FeeAnalyticsReportView": "fee_views",
    "FinanceReportView": "fee_views",
    "FeeDefaultersReportView": "fee_views",
    "EmployeeMasterReportView": "hr_views",
    "HRAttendanceReportView": "hr_views",
    "HRLeaveReportView": "hr_views",
    "PayrollMonthlyReportView": "hr_views",
    "EmployeeSalaryReportView": "hr_views",
    "PayrollSummaryReportView": "hr_views",
    "AllowanceReportView": "hr_views",
    "DeductionReportView": "hr_views",
    "NetSalaryReportView": "hr_views",
    "PaidSalaryReportView": "hr_views",
    "PendingSalaryReportView": "hr_views",
    "StaffMasterReportView": "staff_views",
    "TeacherMasterReportView": "staff_views",
    "StaffAttendanceReportView": "staff_views",
    "TeacherAttendanceReportView": "staff_views",
    "StaffLeaveReportView": "staff_views",
    "TeacherLeaveReportView": "staff_views",
    "TeacherWorkloadReportView": "staff_views",
    "DepartmentReportView": "staff_views",
    "DesignationReportView": "staff_views",
    "StaffJoiningReportView": "staff_views",
    "StaffResignationReportView": "staff_views",
    "ClassStrengthReportView": "academic_views",
    "SectionStrengthReportView": "academic_views",
    "ClassStudentListReportView": "academic_views",
    "GenderDistributionReportView": "academic_views",
    "AcademicPerformanceReportView": "academic_views",
    "PromotionReportView": "academic_views",
    "SubjectListReportView": "academic_views",
    "SubjectAllocationReportView": "academic_views",
    "SubjectPerformanceReportView": "academic_views",
    "TeacherSubjectAllocationReportView": "academic_views",
    "StudentTimetableReportView": "academic_views",
    "ClassTimetableReportView": "academic_views",
    "TeacherTimetableReportView": "academic_views",
    "RoomTimetableReportView": "academic_views",
    "FreePeriodReportView": "academic_views",
    "ParentMasterReportView": "parent_views",
    "ParentStudentRelationshipReportView": "parent_views",
    "ParentContactReportView": "parent_views",
    "ParentWiseStudentsReportView": "parent_views",
    "OutstandingFeesByParentReportView": "parent_views",
    "AttendanceSummaryByParentReportView": "parent_views",
    "AcademicSummaryByParentReportView": "parent_views",
    "LibraryInventoryReportView": "library_views",
    "AvailableBooksReportView": "library_views",
    "IssuedBooksReportView": "library_views",
    "ReturnedBooksReportView": "library_views",
    "OverdueBooksReportView": "library_views",
    "LibraryFinesReportView": "library_views",
    "LibraryActivitySummaryReportView": "library_views",
    "MostBorrowedBooksReportView": "library_views",
    "StudentBorrowingHistoryReportView": "library_views",
    "TeacherBorrowingHistoryReportView": "library_views",
    "StudentTransportListReportView": "transport_views",
    "RouteReportView": "transport_views",
    "VehicleReportView": "transport_views",
    "DriverReportView": "transport_views",
    "PickupDropoffReportView": "transport_views",
    "StudentsByRouteReportView": "transport_views",
    "StudentsByVehicleReportView": "transport_views",
    "TransportFeeReportView": "transport_views",
    "VehicleCapacityReportView": "transport_views",
    "RouteOccupancyReportView": "transport_views",
    "InventoryMasterReportView": "inventory_views",
    "StockReportView": "inventory_views",
    "LowStockReportView": "inventory_views",
    "OutOfStockReportView": "inventory_views",
    "StockMovementReportView": "inventory_views",
    "PurchaseReportView": "inventory_views",
    "IssueReportView": "inventory_views",
    "ReturnReportView": "inventory_views",
    "DamagedItemsReportView": "inventory_views",
    "LostItemsReportView": "inventory_views",
    "CategoryReportView": "inventory_views",
    "SupplierReportView": "inventory_views",
    "InventoryValuationReportView": "inventory_views",
    "DisciplineIncidentsReportView": "discipline_views",
    "StudentIncidentsReportView": "discipline_views",
    "ClassIncidentsReportView": "discipline_views",
    "CampusIncidentsReportView": "discipline_views",
    "IncidentTypeReportView": "discipline_views",
    "DateRangeIncidentsReportView": "discipline_views",
    "WarningReportView": "discipline_views",
    "SuspensionReportView": "discipline_views",
    "RepeatIncidentsReportView": "discipline_views",
    "DisciplinaryHistoryReportView": "discipline_views",
    "BonafideCertificateView": "certificate_views",
    "CharacterCertificateView": "certificate_views",
    "LeavingCertificateView": "certificate_views",
    "TransferCertificateView": "certificate_views",
    "EnrollmentCertificateView": "certificate_views",
    "FeeClearanceCertificateView": "certificate_views",
    "StudentIDCardView": "certificate_views",
    "StaffIDCardView": "certificate_views",
    "CertificateTemplateListView": "certificate_views",
    "CertificateReportView": "certificate_views",
    "CampusStudentCountReportView": "campus_views",
    "CampusAttendanceReportView": "campus_views",
    "CampusAcademicPerformanceReportView": "campus_views",
    "CampusFeeCollectionReportView": "campus_views",
    "CampusOutstandingFeesReportView": "campus_views",
    "CampusStaffCountReportView": "campus_views",
    "CampusAdmissionsReportView": "campus_views",
    "CampusFinancialSummaryReportView": "campus_views",
    "CampusComparisonReportView": "campus_views",
    "CampusDashboardReportView": "campus_views",
    "ReportsRootView": "extended_views",
}

# Cache for imported modules
_module_cache = {}

# Mapping of view names to their module paths
_VIEW_IMPORTS = {
    "ReportsRootView": "extended_views",
    "ChronicAbsenteeReportView": "extended_views",
    "CollectionTrendReportView": "extended_views",
    "DiscountsReportView": "extended_views",
    "EventParticipationReportView": "extended_views",
    "InventoryValueReportView": "extended_views",
    "LibraryOverviewReportView": "extended_views",
    "MaintenanceDueReportView": "extended_views",
    "PayrollSummaryReportView": "extended_views",
    "RouteUtilizationReportView": "extended_views",
    "SmsUsageReportView": "extended_views",
    "TopPerformersReportView": "extended_views",
    "DataBackupView": "export_views",
    "DataExportListView": "export_views",
    "DataExportView": "export_views",
    "PDFExportView": "pdf_views",
    "PrintView": "pdf_views",
    "ReportTemplatePreviewView": "pdf_views",
    "WeeklyReportEmailCronView": "cron_views",
    "AtRiskReportView": "at_risk_views",
    "ImportCommitView": "import_views",
    "ImportPreviewView": "import_views",
    "ImportTemplateView": "import_views",
    "SystemHealthView": "health_views",
    "StudentMasterReportView": "student_views",
    "StudentListReportView": "student_views",
    "AdmissionReportView": "student_views",
    "StudentProfileReportView": "student_views",
    "StudentStatisticsReportView": "student_views",
    "DailyAttendanceReportView": "attendance_views",
    "MonthlyAttendanceReportView": "attendance_views",
    "StudentAttendanceReportView": "attendance_views",
    "ClassAttendanceReportView": "attendance_views",
    "AttendanceAnalyticsReportView": "attendance_views",
    "ChronicAbsenteeReportView": "attendance_views",
    "SubjectAttendanceReportView": "attendance_views",
    "ExamScheduleReportView": "exam_views",
    "ExamMarksReportView": "exam_views",
    "SubjectPerformanceReportView": "exam_views",
    "ClassMarksReportView": "exam_views",
    "StudentResultReportView": "exam_views",
    "ResultAnalyticsReportView": "exam_views",
    "StudentRankingReportView": "exam_views",
    "ReportCardGeneratorView": "exam_views",
    "FeeCollectionReportView": "fee_views",
    "FeeStatusReportView": "fee_views",
    "FeeAnalyticsReportView": "fee_views",
    "FinanceReportView": "fee_views",
    "FeeDefaultersReportView": "fee_views",
    "EmployeeMasterReportView": "hr_views",
    "HRAttendanceReportView": "hr_views",
    "HRLeaveReportView": "hr_views",
    "PayrollMonthlyReportView": "hr_views",
    "EmployeeSalaryReportView": "hr_views",
    "PayrollSummaryReportView": "hr_views",
    "AllowanceReportView": "hr_views",
    "DeductionReportView": "hr_views",
    "NetSalaryReportView": "hr_views",
    "PaidSalaryReportView": "hr_views",
    "PendingSalaryReportView": "hr_views",
    "StaffMasterReportView": "staff_views",
    "TeacherMasterReportView": "staff_views",
    "StaffAttendanceReportView": "staff_views",
    "TeacherAttendanceReportView": "staff_views",
    "StaffLeaveReportView": "staff_views",
    "TeacherLeaveReportView": "staff_views",
    "TeacherWorkloadReportView": "staff_views",
    "DepartmentReportView": "staff_views",
    "DesignationReportView": "staff_views",
    "StaffJoiningReportView": "staff_views",
    "StaffResignationReportView": "staff_views",
    "TeacherWorkloadReportView": "staff_views",
    "DepartmentReportView": "staff_views",
    "DesignationReportView": "staff_views",
    "StaffJoiningReportView": "staff_views",
    "StaffResignationReportView": "staff_views",
    "ClassStrengthReportView": "academic_views",
    "SectionStrengthReportView": "academic_views",
    "ClassStudentListReportView": "academic_views",
    "GenderDistributionReportView": "academic_views",
    "AcademicPerformanceReportView": "academic_views",
    "PromotionReportView": "academic_views",
    "SubjectListReportView": "academic_views",
    "SubjectAllocationReportView": "academic_views",
    "SubjectPerformanceReportView": "academic_views",
    "TeacherSubjectAllocationReportView": "academic_views",
    "StudentTimetableReportView": "academic_views",
    "ClassTimetableReportView": "academic_views",
    "TeacherTimetableReportView": "academic_views",
    "RoomTimetableReportView": "academic_views",
    "FreePeriodReportView": "academic_views",
    "ParentMasterReportView": "parent_views",
    "ParentStudentRelationshipReportView": "parent_views",
    "ParentContactReportView": "parent_views",
    "ParentWiseStudentsReportView": "parent_views",
    "OutstandingFeesByParentReportView": "parent_views",
    "AttendanceSummaryByParentReportView": "parent_views",
    "AcademicSummaryByParentReportView": "parent_views",
    "LibraryInventoryReportView": "library_views",
    "AvailableBooksReportView": "library_views",
    "IssuedBooksReportView": "library_views",
    "ReturnedBooksReportView": "library_views",
    "OverdueBooksReportView": "library_views",
    "LibraryFinesReportView": "library_views",
    "LibraryActivitySummaryReportView": "library_views",
    "MostBorrowedBooksReportView": "library_views",
    "StudentBorrowingHistoryReportView": "library_views",
    "TeacherBorrowingHistoryReportView": "library_views",
    "StudentTransportListReportView": "transport_views",
    "RouteReportView": "transport_views",
    "VehicleReportView": "transport_views",
    "DriverReportView": "transport_views",
    "PickupDropoffReportView": "transport_views",
    "StudentsByRouteReportView": "transport_views",
    "StudentsByVehicleReportView": "transport_views",
    "TransportFeeReportView": "transport_views",
    "VehicleCapacityReportView": "transport_views",
    "RouteOccupancyReportView": "transport_views",
    "InventoryMasterReportView": "inventory_views",
    "StockReportView": "inventory_views",
    "LowStockReportView": "inventory_views",
    "OutOfStockReportView": "inventory_views",
    "StockMovementReportView": "inventory_views",
    "PurchaseReportView": "inventory_views",
    "IssueReportView": "inventory_views",
    "ReturnReportView": "inventory_views",
    "DamagedItemsReportView": "inventory_views",
    "LostItemsReportView": "inventory_views",
    "CategoryReportView": "inventory_views",
    "SupplierReportView": "inventory_views",
    "InventoryValuationReportView": "inventory_views",
    "DisciplineIncidentsReportView": "discipline_views",
    "StudentIncidentsReportView": "discipline_views",
    "ClassIncidentsReportView": "discipline_views",
    "CampusIncidentsReportView": "discipline_views",
    "IncidentTypeReportView": "discipline_views",
    "DateRangeIncidentsReportView": "discipline_views",
    "WarningReportView": "discipline_views",
    "SuspensionReportView": "discipline_views",
    "RepeatIncidentsReportView": "discipline_views",
    "DisciplinaryHistoryReportView": "discipline_views",
    "BonafideCertificateView": "certificate_views",
    "CharacterCertificateView": "certificate_views",
    "LeavingCertificateView": "certificate_views",
    "TransferCertificateView": "certificate_views",
    "EnrollmentCertificateView": "certificate_views",
    "FeeClearanceCertificateView": "certificate_views",
    "StudentIDCardView": "certificate_views",
    "StaffIDCardView": "certificate_views",
    "CertificateTemplateListView": "certificate_views",
    "CertificateReportView": "certificate_views",
    "CampusStudentCountReportView": "campus_views",
    "CampusAttendanceReportView": "campus_views",
    "CampusAcademicPerformanceReportView": "campus_views",
    "CampusFeeCollectionReportView": "campus_views",
    "CampusOutstandingFeesReportView": "campus_views",
    "CampusStaffCountReportView": "campus_views",
    "CampusAdmissionsReportView": "campus_views",
    "CampusFinancialSummaryReportView": "campus_views",
    "CampusComparisonReportView": "campus_views",
    "CampusDashboardReportView": "campus_views",
    "ReportsRootView": "extended_views",
}

# Cache for imported modules
_module_cache = {}

# Mapping of view names to their module paths
_VIEW_IMPORTS = globals()["_VIEW_IMPORTS"]

class _LazyModule(type(sys.modules[__name__])):
    def __getattr__(self, name: str):
        if name in _VIEW_IMPORTS:
            module_name = _VIEW_IMPORTS[name]
            if name not in _module_cache:
                _module_cache[name] = __import__(
                    f"apps.reports.{_VIEW_IMPORTS[name]}",
                    fromlist=[name]
                )
            return getattr(_module_cache[name], name)
        raise AttributeError(f"module 'apps.reports' has no attribute '{name}'")

    def __dir__(self):
        return sorted(set(list(globals().keys()) + list(_VIEW_IMPORTS.keys())))

# Replace the module with our lazy-loading version
import sys
_lazy_module = type(sys.modules[__name__])(__name__)
_lazy_module.__dict__.update(globals())
sys.modules[__name__] = _lazy_module

# Clean up (keep ModuleType for _LazyModule class)
del sys, Any, _VIEW_IMPORTS, _module_cache, _lazy_module, ModuleType