from django.urls import path

from .views import (
    AttendanceReportView,
    EnrollmentReportView,
    FeeCategoryReportView,
    FeesReportView,
    PaymentMethodsReportView,
    ReportGenerateView,
    ReportTemplateDetailView,
    ReportTemplateListView,
    ResultsReportView,
    StaffReportView,
    StudentStatusReportView,
    SubjectPerformanceReportView,
)
from .export_views import (
    DataBackupView,
    DataExportListView,
    DataExportView,
)
from .health_views import SystemHealthView


urlpatterns = [
    path(
        "enrollment/",
        EnrollmentReportView.as_view(),
        name="report-enrollment",
    ),
    path(
        "attendance/",
        AttendanceReportView.as_view(),
        name="report-attendance",
    ),
    path(
        "results/",
        ResultsReportView.as_view(),
        name="report-results",
    ),
    path(
        "fees/",
        FeesReportView.as_view(),
        name="report-fees",
    ),
    path(
        "staff/",
        StaffReportView.as_view(),
        name="report-staff",
    ),
    path(
        "subjects/",
        SubjectPerformanceReportView.as_view(),
        name="report-subject-performance",
    ),
    path(
        "payments/",
        PaymentMethodsReportView.as_view(),
        name="report-payment-methods",
    ),
    path(
        "student-status/",
        StudentStatusReportView.as_view(),
        name="report-student-status",
    ),
    path(
        "fee-categories/",
        FeeCategoryReportView.as_view(),
        name="report-fee-categories",
    ),
    path(
        "templates/",
        ReportTemplateListView.as_view(),
        name="report-template-list",
    ),
    path(
        "templates/<int:pk>/",
        ReportTemplateDetailView.as_view(),
        name="report-template-detail",
    ),
    path(
        "generate/",
        ReportGenerateView.as_view(),
        name="report-generate",
    ),
    path(
        "export/",
        DataExportListView.as_view(),
        name="data-export-list",
    ),
    path(
        "export/<str:export_key>/",
        DataExportView.as_view(),
        name="data-export",
    ),
    path(
        "backup/",
        DataBackupView.as_view(),
        name="data-backup",
    ),
    path(
        "health/",
        SystemHealthView.as_view(),
        name="system-health",
    ),
]
