from django.urls import path

from .extended_views import (
    ChronicAbsenteeReportView,
    CollectionTrendReportView,
    DiscountsReportView,
    EventParticipationReportView,
    InventoryValueReportView,
    LibraryOverviewReportView,
    MaintenanceDueReportView,
    PayrollSummaryReportView,
    RouteUtilizationReportView,
    SmsUsageReportView,
    TopPerformersReportView,
)
from .views import (
    AttendanceReportView,
    ClassPerformanceReportView,
    EnrollmentReportView,
    FeeCategoryReportView,
    FeeDefaultersReportView,
    FeesReportView,
    PaymentMethodsReportView,
    ReportGenerateView,
    ReportTemplateDetailView,
    ReportTemplateListView,
    ResultsReportView,
    StaffReportView,
    StudentProgressTrendReportView,
    StudentStatusReportView,
    SubjectPerformanceReportView,
    TeacherWorkloadReportView,
)
from .export_views import (
    DataBackupView,
    DataExportListView,
    DataExportView,
)
from .health_views import SystemHealthView


urlpatterns = [
    path(
        "enrollment/",
        EnrollmentReportView.as_view(),
        name="report-enrollment",
    ),
    path(
        "attendance/",
        AttendanceReportView.as_view(),
        name="report-attendance",
    ),
    path(
        "results/",
        ResultsReportView.as_view(),
        name="report-results",
    ),
    path(
        "fees/",
        FeesReportView.as_view(),
        name="report-fees",
    ),
    path(
        "staff/",
        StaffReportView.as_view(),
        name="report-staff",
    ),
    path(
        "subjects/",
        SubjectPerformanceReportView.as_view(),
        name="report-subject-performance",
    ),
    path(
        "payments/",
        PaymentMethodsReportView.as_view(),
        name="report-payment-methods",
    ),
    path(
        "student-status/",
        StudentStatusReportView.as_view(),
        name="report-student-status",
    ),
    path(
        "fee-categories/",
        FeeCategoryReportView.as_view(),
        name="report-fee-categories",
    ),
    path(
        "fee-defaulters/",
        FeeDefaultersReportView.as_view(),
        name="report-fee-defaulters",
    ),
    path(
        "teacher-workload/",
        TeacherWorkloadReportView.as_view(),
        name="report-teacher-workload",
    ),
    path(
        "class-performance/",
        ClassPerformanceReportView.as_view(),
        name="report-class-performance",
    ),
    path(
        "student-progress/",
        StudentProgressTrendReportView.as_view(),
        name="report-student-progress",
    ),
    path(
        "collection-trend/",
        CollectionTrendReportView.as_view(),
        name="report-collection-trend",
    ),
    path(
        "discounts/",
        DiscountsReportView.as_view(),
        name="report-discounts",
    ),
    path(
        "chronic-absentee/",
        ChronicAbsenteeReportView.as_view(),
        name="report-chronic-absentee",
    ),
    path(
        "payroll-summary/",
        PayrollSummaryReportView.as_view(),
        name="report-payroll-summary",
    ),
    path(
        "library/",
        LibraryOverviewReportView.as_view(),
        name="report-library",
    ),
    path(
        "route-utilization/",
        RouteUtilizationReportView.as_view(),
        name="report-route-utilization",
    ),
    path(
        "inventory-value/",
        InventoryValueReportView.as_view(),
        name="report-inventory-value",
    ),
    path(
        "maintenance-due/",
        MaintenanceDueReportView.as_view(),
        name="report-maintenance-due",
    ),
    path(
        "event-participation/",
        EventParticipationReportView.as_view(),
        name="report-event-participation",
    ),
    path(
        "sms-usage/",
        SmsUsageReportView.as_view(),
        name="report-sms-usage",
    ),
    path(
        "top-performers/",
        TopPerformersReportView.as_view(),
        name="report-top-performers",
    ),
    path(
        "templates/",
        ReportTemplateListView.as_view(),
        name="report-template-list",
    ),
    path(
        "templates/<int:pk>/",
        ReportTemplateDetailView.as_view(),
        name="report-template-detail",
    ),
    path(
        "generate/",
        ReportGenerateView.as_view(),
        name="report-generate",
    ),
    path(
        "export/",
        DataExportListView.as_view(),
        name="data-export-list",
    ),
    path(
        "export/<str:export_key>/",
        DataExportView.as_view(),
        name="data-export",
    ),
    path(
        "backup/",
        DataBackupView.as_view(),
        name="data-backup",
    ),
    path(
        "health/",
        SystemHealthView.as_view(),
        name="system-health",
    ),
]
