"""Reports app views - consolidated exports for URL routing."""

from rest_framework.views import APIView
from rest_framework.response import Response

from apps.accounts.permissions import IsAccountantRole

# REPORT_VIEW_MAP maps report type strings to view classes for the weekly email cron
REPORT_VIEW_MAP = {
    "enrollment": "apps.reports.student_views.StudentMasterReportView",
    "attendance": "apps.reports.attendance_views.MonthlyAttendanceReportView",
    "fees": "apps.reports.fee_views.FeesReportView",
    "fee_defaulters": "apps.reports.fee_views.FeeDefaultersReportView",
}

class ReportsRootView(APIView):
    """Root endpoint for Reports API."""
    permission_classes = [IsAccountantRole]

    def get(self, request):
        return Response({
            "message": "Reports API",
            "endpoints": {
                "enrollment": "/api/reports/enrollment/",
                "attendance": "/api/reports/attendance/",
                "results": "/api/reports/results/",
                "fees": "/api/reports/fees/",
                "staff": "/api/reports/staff/",
                "subjects": "/api/reports/subjects/",
                "payments": "/api/reports/payments/",
                "student_status": "/api/reports/student-status/",
                "fee_categories": "/api/reports/fee-categories/",
                "fee_defaulters": "/api/reports/fee-defaulters/",
                "teacher_workload": "/api/reports/teacher-workload/",
                "class_performance": "/api/reports/class-performance/",
                "student_progress": "/api/reports/student-progress/",
                "subjects": "/api/reports/subjects/",
                "payments": "/api/reports/payments/",
                "student_status": "/api/reports/student-status/",
                "fee_categories": "/api/reports/fee-categories/",
                "fee_defaulters": "/api/reports/fee-defaulters/",
                "teacher_workload": "/api/reports/teacher-workload/",
                "class_performance": "/api/reports/class-performance/",
                "student_progress": "/api/reports/student-progress/",
                "subjects": "/api/reports/subjects/",
                "payments": "/api/reports/payments/",
                "student_status": "/api/reports/student-status/",
                "fee_categories": "/api/reports/fee-categories/",
                "fee_defaulters": "/api/reports/fee-defaulters/",
                "teacher_workload": "/api/reports/teacher-workload/",
                "class_performance": "/api/reports/class-performance/",
                "student_progress": "/api/reports/student-progress/",
                "subjects": "/api/reports/subjects/",
                "payments": "/api/reports/payments/",
                "student_status": "/api/reports/student-status/",
                "fee_categories": "/api/reports/fee-categories/",
                "fee_defaulters": "/api/reports/fee-defaulters/",
                "teacher_workload": "/api/reports/teacher-workload/",
                "class_performance": "/api/reports/class-performance/",
                "student_progress": "/api/reports/student-progress/",
                "subjects": "/api/reports/subjects/",
                "payments": "/api/reports/payments/",
                "student_status": "/api/reports/student-status/",
                "fee_categories": "/api/reports/fee-categories/",
                "fee_defaulters": "/api/reports/fee-defaulters/",
                "teacher_workload": "/api/reports/teacher-workload/",
                "library": {
                    "inventory": "/api/reports/library/inventory/",
                    "available": "/api/reports/library/available/",
                    "issued": "/api/reports/library/issued/",
                    "returned": "/api/reports/library/returned/",
                    "overdue": "/api/reports/library/overdue/",
                    "fines": "/api/reports/library/fines/",
                    "activity": "/api/reports/library/activity/",
                    "most_borrowed": "/api/reports/library/most-borrowed/",
                    "student_history": "/api/reports/library/student-history/",
                    "teacher_history": "/api/reports/library/teacher-history/",
                }
            }
        })

# Re-export all views from their respective modules
from .extended_views import (
    ChronicAbsenteeReportView,
    CollectionTrendReportView,
    DiscountsReportView,
    EventParticipationReportView,
    InventoryValueReportView,
    LibraryOverviewReportView,
    MaintenanceDueReportView,
    PayrollSummaryReportView,
    RouteUtilizationReportView,
    SmsUsageReportView,
    TopPerformersReportView,
)

from .export_views import (
    DataBackupView,
    DataExportListView,
    DataExportView,
)

from .pdf_views import (
    PDFExportView,
    PrintView,
    ReportTemplatePreviewView,
)

from .cron_views import WeeklyReportEmailCronView

from .at_risk_views import AtRiskReportView

from .import_views import (
    ImportCommitView,
    ImportPreviewView,
    ImportTemplateView,
)

from .health_views import SystemHealthView

from .student_views import (
    StudentMasterReportView,
    StudentListReportView,
    AdmissionReportView,
    StudentProfileReportView,
    StudentStatisticsReportView,
)

from .attendance_views import (
    DailyAttendanceReportView,
    MonthlyAttendanceReportView,
    StudentAttendanceReportView,
    ClassAttendanceReportView,
    AttendanceAnalyticsReportView,
    ChronicAbsenteeReportView,
    SubjectAttendanceReportView,
)

from .exam_views import (
    ExamScheduleReportView,
    ExamMarksReportView,
    SubjectPerformanceReportView,
    ClassMarksReportView,
    StudentResultReportView,
    ResultAnalyticsReportView,
    StudentRankingReportView,
    ReportCardGeneratorView,
)

from .fee_views import (
    FeeCollectionReportView,
    FeeStatusReportView,
    FeeAnalyticsReportView,
    FinanceReportView,
    FeeDefaultersReportView,
)

from .hr_views import (
    EmployeeMasterReportView,
    HRAttendanceReportView,
    HRLeaveReportView,
    PayrollMonthlyReportView,
    EmployeeSalaryReportView,
    PayrollSummaryReportView,
    AllowanceReportView,
    DeductionReportView,
    NetSalaryReportView,
    PaidSalaryReportView,
    PendingSalaryReportView,
)

from .staff_views import (
    StaffMasterReportView,
    TeacherMasterReportView,
    StaffAttendanceReportView,
    TeacherAttendanceReportView,
    StaffLeaveReportView,
    TeacherLeaveReportView,
    TeacherWorkloadReportView,
    DepartmentReportView,
    DesignationReportView,
    StaffJoiningReportView,
    StaffResignationReportView,
    TeacherWorkloadReportView,
    DepartmentReportView,
    DesignationReportView,
    StaffJoiningReportView,
    StaffResignationReportView,
)

from .academic_views import (
    ClassStrengthReportView,
    SectionStrengthReportView,
    ClassStudentListReportView,
    GenderDistributionReportView,
    AcademicPerformanceReportView,
    PromotionReportView,
    SubjectListReportView,
    SubjectAllocationReportView,
    SubjectPerformanceReportView,
    TeacherSubjectAllocationReportView,
    StudentTimetableReportView,
    ClassTimetableReportView,
    TeacherTimetableReportView,
    RoomTimetableReportView,
    FreePeriodReportView,
)

from .parent_views import (
    ParentMasterReportView,
    ParentStudentRelationshipReportView,
    ParentContactReportView,
    ParentWiseStudentsReportView,
    OutstandingFeesByParentReportView,
    AttendanceSummaryByParentReportView,
    AcademicSummaryByParentReportView,
)

from .library_views import (
    LibraryInventoryReportView,
    AvailableBooksReportView,
    IssuedBooksReportView,
    ReturnedBooksReportView,
    OverdueBooksReportView,
    LibraryFinesReportView,
    LibraryActivitySummaryReportView,
    MostBorrowedBooksReportView,
    StudentBorrowingHistoryReportView,
    TeacherBorrowingHistoryReportView,
)

from .transport_views import (
    StudentTransportListReportView,
    RouteReportView,
    VehicleReportView,
    DriverReportView,
    PickupDropoffReportView,
    StudentsByRouteReportView,
    StudentsByVehicleReportView,
    TransportFeeReportView,
    VehicleCapacityReportView,
    RouteOccupancyReportView,
)

from .inventory_views import (
    InventoryMasterReportView,
    StockReportView,
    LowStockReportView,
    OutOfStockReportView,
    StockMovementReportView,
    PurchaseReportView,
    IssueReportView,
    ReturnReportView,
    DamagedItemsReportView,
    LostItemsReportView,
    CategoryReportView,
    SupplierReportView,
    InventoryValuationReportView,
)

from .discipline_views import (
    DisciplineIncidentsReportView,
    StudentIncidentsReportView,
    ClassIncidentsReportView,
    CampusIncidentsReportView,
    IncidentTypeReportView,
    DateRangeIncidentsReportView,
    WarningReportView,
    SuspensionReportView,
    RepeatIncidentsReportView,
    DisciplinaryHistoryReportView,
)

from .certificate_views import (
    BonafideCertificateView,
    CharacterCertificateView,
    LeavingCertificateView,
    TransferCertificateView,
    EnrollmentCertificateView,
    FeeClearanceCertificateView,
    StudentIDCardView,
    StaffIDCardView,
    CertificateTemplateListView,
    CertificateReportView,
)

from .campus_views import (
    CampusStudentCountReportView,
    CampusAttendanceReportView,
    CampusAcademicPerformanceReportView,
    CampusFeeCollectionReportView,
    CampusOutstandingFeesReportView,
    CampusStaffCountReportView,
    CampusAdmissionsReportView,
    CampusFinancialSummaryReportView,
    CampusComparisonReportView,
    CampusDashboardReportView,
)



__all__ = [
    "ReportsRootView",
    "ChronicAbsenteeReportView",
    "CollectionTrendReportView",
    "DiscountsReportView",
    "EventParticipationReportView",
    "InventoryValueReportView",
    "LibraryOverviewReportView",
    "MaintenanceDueReportView",
    "PayrollSummaryReportView",
    "RouteUtilizationReportView",
    "SmsUsageReportView",
    "TopPerformersReportView",
    "DataBackupView",
    "DataExportListView",
    "DataExportView",
    "PDFExportView",
    "PrintView",
    "ReportTemplatePreviewView",
    "WeeklyReportEmailCronView",
    "AtRiskReportView",
    "ImportCommitView",
    "ImportPreviewView",
    "ImportTemplateView",
    "SystemHealthView",
    "StudentMasterReportView",
    "StudentListReportView",
    "AdmissionReportView",
    "StudentProfileReportView",
    "StudentStatisticsReportView",
    "DailyAttendanceReportView",
    "MonthlyAttendanceReportView",
    "StudentAttendanceReportView",
    "ClassAttendanceReportView",
    "AttendanceAnalyticsReportView",
    "ChronicAbsenteeReportView",
    "SubjectAttendanceReportView",
    "ExamScheduleReportView",
    "ExamMarksReportView",
    "SubjectPerformanceReportView",
    "ClassMarksReportView",
    "StudentResultReportView",
    "ResultAnalyticsReportView",
    "StudentRankingReportView",
    "ReportCardGeneratorView",
    "FeeCollectionReportView",
    "FeeStatusReportView",
    "FeeAnalyticsReportView",
    "FinanceReportView",
    "FeeDefaultersReportView",
    "EmployeeMasterReportView",
    "HRAttendanceReportView",
    "HRLeaveReportView",
    "PayrollMonthlyReportView",
    "EmployeeSalaryReportView",
    "PayrollSummaryReportView",
    "AllowanceReportView",
    "DeductionReportView",
    "NetSalaryReportView",
    "PaidSalaryReportView",
    "PendingSalaryReportView",
    "StaffMasterReportView",
    "TeacherMasterReportView",
    "StaffAttendanceReportView",
    "TeacherAttendanceReportView",
    "StaffLeaveReportView",
    "TeacherLeaveReportView",
    "TeacherWorkloadReportView",
    "DepartmentReportView",
    "DesignationReportView",
    "StaffJoiningReportView",
    "StaffResignationReportView",
    "TeacherWorkloadReportView",
    "DepartmentReportView",
    "DesignationReportView",
    "StaffJoiningReportView",
    "StaffResignationReportView",
    "ClassStrengthReportView",
    "SectionStrengthReportView",
    "ClassStudentListReportView",
    "GenderDistributionReportView",
    "AcademicPerformanceReportView",
    "PromotionReportView",
    "SubjectListReportView",
    "SubjectAllocationReportView",
    "SubjectPerformanceReportView",
    "TeacherSubjectAllocationReportView",
    "StudentTimetableReportView",
    "ClassTimetableReportView",
    "TeacherTimetableReportView",
    "RoomTimetableReportView",
    "FreePeriodReportView",
    "ParentMasterReportView",
    "ParentStudentRelationshipReportView",
    "ParentContactReportView",
    "ParentWiseStudentsReportView",
    "OutstandingFeesByParentReportView",
    "AttendanceSummaryByParentReportView",
    "AcademicSummaryByParentReportView",
    "LibraryInventoryReportView",
    "AvailableBooksReportView",
    "IssuedBooksReportView",
    "ReturnedBooksReportView",
    "OverdueBooksReportView",
    "LibraryFinesReportView",
    "LibraryActivitySummaryReportView",
    "MostBorrowedBooksReportView",
    "StudentBorrowingHistoryReportView",
    "TeacherBorrowingHistoryReportView",
    "StudentTransportListReportView",
    "RouteReportView",
    "VehicleReportView",
    "DriverReportView",
    "PickupDropoffReportView",
    "StudentsByRouteReportView",
    "StudentsByVehicleReportView",
    "TransportFeeReportView",
    "VehicleCapacityReportView",
    "RouteOccupancyReportView",
    "InventoryMasterReportView",
    "StockReportView",
    "LowStockReportView",
    "OutOfStockReportView",
    "StockMovementReportView",
    "PurchaseReportView",
    "IssueReportView",
    "ReturnReportView",
    "DamagedItemsReportView",
    "LostItemsReportView",
    "CategoryReportView",
    "SupplierReportView",
    "InventoryValuationReportView",
    "DisciplineIncidentsReportView",
    "StudentIncidentsReportView",
    "ClassIncidentsReportView",
    "CampusIncidentsReportView",
    "IncidentTypeReportView",
    "DateRangeIncidentsReportView",
    "WarningReportView",
    "SuspensionReportView",
    "RepeatIncidentsReportView",
    "DisciplinaryHistoryReportView",
    "BonafideCertificateView",
    "CharacterCertificateView",
    "LeavingCertificateView",
    "TransferCertificateView",
    "EnrollmentCertificateView",
    "FeeClearanceCertificateView",
    "StudentIDCardView",
    "StaffIDCardView",
    "CertificateTemplateListView",
    "CertificateReportView",
    "CampusStudentCountReportView",
    "CampusAttendanceReportView",
    "CampusAcademicPerformanceReportView",
    "CampusFeeCollectionReportView",
    "CampusOutstandingFeesReportView",
    "CampusStaffCountReportView",
    "CampusAdmissionsReportView",
    "CampusFinancialSummaryReportView",
    "CampusComparisonReportView",
    "CampusDashboardReportView",
    "ReportsRootView",
]