# Generated by Django 6.1 on 2026-08-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['student__first_name', 'student__last_name']},
        ),
    ]
