# Generated by Django 6.1 on 2026-08-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_primary_guardian_links(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    StudentGuardian = apps.get_model("students", "StudentGuardian")

    StudentGuardian.objects.bulk_create(
        [
            StudentGuardian(
                student_id=student.id,
                guardian_id=student.guardian_id,
                relationship="Primary guardian",
                is_primary=True,
                is_emergency_contact=True,
            )
            for student in Student.objects.only("id", "guardian_id")
            if student.guardian_id
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_institution_settings'),
        ('students', '0005_student_membership_primary_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.campus')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.class')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='students.guardian')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admission_applications', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.section')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activated', 'Activated'), ('inactive', 'Marked inactive'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_from', to='schools.campus')),
                ('from_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_from', to='students.enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='students.student')),
                ('to_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_to', to='schools.campus')),
                ('to_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_to', to='students.enrollment')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_pick_up', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student')),
            ],
            options={
                'ordering': ['-is_primary', 'guardian__name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian_link')],
            },
        ),
        migrations.RunPython(
            backfill_primary_guardian_links,
            migrations.RunPython.noop,
        ),
    ]
