# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_institution_to_all_models'),
        ('schools', '0008_add_institution_to_all_models'),
        ('students', '0008_enrollment_roll_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications_tenant', to='schools.school'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_leave_requests', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_lifecycle_events', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institution', 'admission_number'), name='unique_admission_number_per_institution'),
        ),
    ]
