# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_is_paused_school_paused_at_school_paused_by_and_more'),
        ('students', '0009_add_institution_to_all_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressionrecord_deleted', to=settings.AUTH_USER_MODEL)),
                ('action', models.CharField(choices=[('promotion', 'Promotion'), ('demotion', 'Demotion'), ('class_transfer', 'Class Transfer'), ('section_transfer', 'Section Transfer'), ('campus_transfer', 'Campus Transfer')], max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_from', to='schools.academicyear')),
                ('from_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_from', to='schools.campus')),
                ('from_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_from', to='schools.class')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_from', to='schools.section')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_progressions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_records', to='students.student')),
                ('to_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_to', to='schools.academicyear')),
                ('to_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_to', to='schools.campus')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_to', to='schools.class')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_to', to='schools.section')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['student', 'action'], name='prog_student_action_idx'),
                    models.Index(fields=['from_academic_year', 'to_academic_year'], name='prog_years_idx'),
                    models.Index(fields=['from_campus', 'to_campus'], name='prog_campuses_idx'),
                ],
            },
        ),
    ]
