# Generated by Django 6.1 on 2026-08-29 02:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffattendance_deleted_at_and_more'),
        ('schools', '0019_subjectoffering_is_compulsory_and_more'),
        ('students', '0010_progressionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('enrollment_date', models.DateField()),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('promoted', 'Promoted'), ('retained', 'Retained')], default='completed', max_length=20)),
                ('promotion_status', models.CharField(blank=True, choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('final_grade', models.CharField(blank=True, max_length=10)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='CampusTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inquiry_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('website', 'Website'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('email', 'Email'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('event', 'Event/Open House'), ('other', 'Other')], default='website', max_length=20)),
                ('source_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('application_started', 'Application Started'), ('converted', 'Converted to Application'), ('lost', 'Lost'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transfer_type', models.CharField(choices=[('section', 'Section Transfer'), ('class', 'Class Transfer')], max_length=10)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('graduation_status', models.CharField(choices=[('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('expelled', 'Expelled'), ('transferred_out', 'Transferred Out')], max_length=20)),
                ('graduation_date', models.DateField()),
                ('final_grade', models.CharField(blank=True, max_length=10)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade_letter', models.CharField(blank=True, max_length=5)),
                ('conduct', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('personal_phone', models.CharField(blank=True, max_length=30)),
                ('current_address', models.TextField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('current_institution', models.CharField(blank=True, max_length=200)),
                ('current_program', models.CharField(blank=True, max_length=200)),
                ('current_occupation', models.CharField(blank=True, max_length=200)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('admission_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=30)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('admission_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('reason', models.CharField(choices=[('transfer', 'Transfer to Another School'), ('graduation', 'Graduation'), ('withdrawal', 'Withdrawal'), ('expulsion', 'Expulsion'), ('other', 'Other')], default='transfer', max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('final_grade', models.CharField(blank=True, max_length=10)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conduct', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressionrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['campus', 'status'], name='enrollment_campus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_obj', 'section', 'status'], name='enrollment_class_section_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'status'], name='enrollment_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'status'], name='student_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['primary_campus', 'status'], name='student_campus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='student_name_idx'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history_records', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history_records', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history_records', to='schools.class'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history_records', to='schools.section'),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus_transfers', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_campus_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='from_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_campus_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_campus_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campus_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='admission_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiry', to='students.admissionapplication'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.campus'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.class'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='schools.school'),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_transfers', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_section_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='from_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='schools.section'),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_section_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_section_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='sectiontransfer',
            name='to_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='schools.section'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='final_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduated_students', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='final_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduated_students', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='final_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduated_students', to='schools.class'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='final_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduated_students', to='schools.section'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_alumni_records', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentalumni',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_alumni_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_certificates', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_certificates', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_certificates', to='schools.class'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transfer_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_certificates', to='schools.section'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='academichistory',
            index=models.Index(fields=['student', 'academic_year'], name='academic_hist_stu_year_idx'),
        ),
        migrations.AddIndex(
            model_name='academichistory',
            index=models.Index(fields=['campus', 'academic_year', 'final_status'], name='academic_hist_cmp_yr_sts_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['student', 'status'], name='ct_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['from_campus', 'to_campus', 'status'], name='ct_campus_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['academic_year', 'status'], name='ct_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['institution', 'status'], name='inquiry_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'created_at'], name='inquiry_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['phone', 'email'], name='inquiry_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiontransfer',
            index=models.Index(fields=['student', 'status'], name='st_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiontransfer',
            index=models.Index(fields=['from_section', 'to_section', 'status'], name='st_section_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentalumni',
            index=models.Index(fields=['institution', 'graduation_status'], name='alumni_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentalumni',
            index=models.Index(fields=['graduation_date'], name='alumni_grad_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentalumni',
            index=models.Index(fields=['is_active'], name='alumni_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transfercertificate',
            index=models.Index(fields=['student', 'status'], name='tc_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transfercertificate',
            index=models.Index(fields=['campus', 'academic_year', 'status'], name='tc_campus_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transfercertificate',
            index=models.Index(fields=['verification_code'], name='tc_verification_code_idx'),
        ),
    ]
