# Generated by Django 6.1 on 2026-09-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_subjectoffering_campus'),
        ('students', '0011_academichistory_campustransfer_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='schools.school'),
        ),
    ]
