# Generated by Django 6.1 on 2026-09-11 14:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_transfercertificate_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(
                help_text='School-scoped admission number. Must be unique within the same institution.',
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(
                fields=['institution', 'admission_number'],
                name='unique_admission_number_per_institution',
            ),
        ),
    ]