# Generated by Django 6.1 on 2026-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment Report'), ('attendance', 'Attendance Report'), ('results', 'Results Report'), ('fees', 'Fees Report'), ('staff', 'Staff Report'), ('subjects', 'Subject Performance'), ('payments', 'Payment Methods'), ('student_status', 'Student Status'), ('fee_categories', 'Fee Categories'), ('fee_defaulters', 'Fee Defaulters'), ('teacher_workload', 'Teacher Workload'), ('class_performance', 'Class Performance'), ('student_progress', 'Student Progress'), ('collection_trend', 'Collection Trend'), ('discounts', 'Discounts & Concessions'), ('chronic_absentee', 'Chronic Absentees'), ('payroll_summary', 'Payroll Summary'), ('library_overview', 'Library Overview'), ('route_utilization', 'Route Utilization'), ('inventory_value', 'Inventory Value'), ('maintenance_due', 'Maintenance Due'), ('event_participation', 'Event Participation'), ('sms_usage', 'SMS Usage'), ('top_performers', 'Top Performers')], max_length=30),
        ),
    ]
