from django.urls import path

from .views import (
    AnnouncementDetailView,
    AnnouncementListView,
    MessageDetailView,
    MessageListView,
    MessageRecipientsView,
    MessageThreadView,
    MessageUnreadCountView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
)
from .sms_views import (
    NotificationPreferenceView,
    SMSBroadcastView,
    SMSLogListView,
)
from .template_views import (
    MessageTemplateDetailView,
    MessageTemplateListView,
    MessageTemplatePreviewView,
)


urlpatterns = [
    path(
        "announcements/",
        AnnouncementListView.as_view(),
        name="announcement-list",
    ),
    path(
        "announcements/<int:pk>/",
        AnnouncementDetailView.as_view(),
        name="announcement-detail",
    ),
    path(
        "notifications/",
        NotificationListView.as_view(),
        name="notification-list",
    ),
    path(
        "notifications/read-all/",
        NotificationMarkAllReadView.as_view(),
        name="notification-read-all",
    ),
    path(
        "notifications/<int:pk>/read/",
        NotificationMarkReadView.as_view(),
        name="notification-read",
    ),
    path(
        "messages/",
        MessageListView.as_view(),
        name="message-list",
    ),
    path(
        "messages/recipients/",
        MessageRecipientsView.as_view(),
        name="message-recipients",
    ),
    path(
        "messages/unread-count/",
        MessageUnreadCountView.as_view(),
        name="message-unread-count",
    ),
    path(
        "messages/<int:pk>/",
        MessageDetailView.as_view(),
        name="message-detail",
    ),
    path(
        "messages/<int:pk>/thread/",
        MessageThreadView.as_view(),
        name="message-thread",
    ),
    path(
        "sms/send/",
        SMSBroadcastView.as_view(),
        name="sms-send",
    ),
    path(
        "sms/logs/",
        SMSLogListView.as_view(),
        name="sms-logs",
    ),
    path(
        "notification-preferences/",
        NotificationPreferenceView.as_view(),
        name="notification-preferences",
    ),
    path(
        "templates/",
        MessageTemplateListView.as_view(),
        name="message-template-list",
    ),
    path(
        "templates/<int:pk>/",
        MessageTemplateDetailView.as_view(),
        name="message-template-detail",
    ),
    path(
        "templates/<int:pk>/preview/",
        MessageTemplatePreviewView.as_view(),
        name="message-template-preview",
    ),
]
