# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_add_institution_to_all_models'),
        ('transport', '0003_driver_campus_route_campus_vehicle_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_tenant', to='schools.school'),
        ),
        migrations.AddField(
            model_name='route',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes_tenant', to='schools.school'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_tenant', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('institution', 'plate_number'), name='unique_vehicle_plate_per_institution'),
        ),
    ]
