export const CORE = {
  SUPER_ADMIN: {
    label: "Platform Administrator",
    username: "FrostFire",
    superuser: true,
    navGroups: {
      People: ["Students", "Admissions", "Teachers", "Staff", "Staff Leave & Attendance", "Health Records", "Human Resources", "Parent Portal", "My Profile"],
      Academics: ["Attendance", "Discipline", "Exams", "Homework", "Online Courses", "Report Cards", "Timetable", "Assignments", "Academics"],
      More: ["Finance", "Student Fees", "Bulk Finance", "Payroll", "Reports", "Report Builder", "Data Export", "Data Import", "Library", "Transport", "Inventory", "Documents", "Campuses", "Campus Dashboard", "Executive Dashboard", "Alumni", "Hostel", "Messages", "SMS", "Templates", "Announcements", "Events", "Helpdesk", "Visitors", "Digital IDs", "AI Assistant", "Pending Approvals", "Workflow Definitions", "Settings", "Branding", "Schools", "System Health", "Audit Logs"],
    },
    corePages: [
      "/",
      "/students",
      "/teachers",
      "/staff",
      "/attendance",
      "/exams",
      "/report-cards",
      "/finance",
      "/hr",
      "/payroll",
      "/reports",
      "/documents",
      "/events",
      "/messages",
      "/timetable",
      "/library",
      "/transport",
      "/inventory",
      "/helpdesk",
      "/visitors",
      "/digital-ids",
      "/workflow/definitions",
      "/workflow/approvals",
      "/hostel",
      "/health-records",
      "/parent-portal",
      "/settings",
      "/branding",
      "/audit-logs",
      "/profile",
      "/campuses",
      "/admissions",
      "/academics",
    ],
    tailPages: [
      "/finance/student-fees",
      "/finance/bulk",
      "/report-builder",
      "/data-export",
      "/data-import",
      "/sms",
      "/templates",
      "/campus-dashboard",
      "/executive-dashboard",
      "/alumni",
      "/announcements",
      "/ai-assistant",
      "/staff-operations",
      "/assignments",
      "/discipline",
      "/homework",
      "/lms",
      "/tenants",
      "/health",
    ],
  },
  ADMIN: {
    label: "Principal",
    username: "Flora",
    superuser: false,
    navGroups: {
      People: ["Students", "Admissions", "Teachers", "Staff", "Staff Leave & Attendance", "Health Records", "Human Resources", "My Profile"],
      Academics: ["Attendance", "Discipline", "Exams", "Homework", "Online Courses", "Report Cards", "Timetable", "Assignments", "Academics"],
      More: ["Finance", "Payroll", "Reports", "Report Builder", "Library", "Transport", "Inventory", "Documents", "Campuses", "Campus Dashboard", "Executive Dashboard", "Alumni", "Hostel", "Messages", "Announcements", "Events", "Helpdesk", "Visitors", "Digital IDs", "AI Assistant", "Pending Approvals", "Workflow Definitions", "Settings"],
    },
    allowed: [
      "/",
      "/students",
      "/teachers",
      "/staff",
      "/attendance",
      "/exams",
      "/report-cards",
      "/finance",
      "/hr",
      "/payroll",
      "/reports",
      "/documents",
      "/messages",
      "/timetable",
      "/profile",
      "/campuses",
    ],
    deniedUI: ["/audit-logs", "/branding", "/sms", "/templates", "/data-export", "/data-import", "/tenants"],
  },
  TEACHER: {
    label: "Teacher",
    username: "SA-EMP-0001",
    superuser: false,
    navGroups: {
      People: ["Students", "Health Records", "My Profile"],
      Academics: ["Attendance", "Discipline", "Exams", "Homework", "Online Courses", "Report Cards", "Timetable"],
      Communication: ["Messages", "Announcements", "Events"],
      More: ["Helpdesk", "AI Assistant"],
    },
    allowed: [
      "/",
      "/students",
      "/health-records",
      "/attendance",
      "/exams",
      "/report-cards",
      "/timetable",
      "/messages",
      "/events",
      "/profile",
      "/helpdesk",
    ],
    deniedUI: ["/finance", "/payroll", "/hr", "/staff", "/settings", "/campuses", "/report-builder", "/library"],
  },
  STUDENT: {
    label: "Student",
    username: "SA-ST-0001",
    superuser: false,
    navGroups: {
      People: ["Students", "My Profile"],
      Academics: ["Homework", "Online Courses", "Timetable"],
      Communication: ["Messages", "Announcements", "Events"],
      More: ["AI Assistant"],
    },
    allowed: [
      "/",
      "/students",
      "/homework",
      "/lms",
      "/timetable",
      "/messages",
      "/announcements",
      "/events",
      "/profile",
      "/ai-assistant",
    ],
    deniedUI: [
      "/finance",
      "/payroll",
      "/hr",
      "/staff",
      "/attendance",
      "/exams",
      "/report-cards",
      "/settings",
      "/teachers",
      "/campuses",
    ],
  },
  STAFF: {
    label: "Staff",
    username: "DI-EMP-0001",
    superuser: false,
    navGroups: {
      People: ["My Profile"],
      Academics: ["Timetable"],
      Communication: ["Messages", "Announcements", "Events"],
      "Support & Security": ["Helpdesk", "Visitors", "Digital IDs", "AI Assistant"],
    },
    allowed: [
      "/",
      "/profile",
      "/timetable",
      "/messages",
      "/announcements",
      "/events",
      "/helpdesk",
      "/visitors",
      "/digital-ids",
      "/ai-assistant",
    ],
    deniedUI: [
      "/finance",
      "/payroll",
      "/hr",
      "/staff",
      "/attendance",
      "/exams",
      "/report-cards",
      "/settings",
      "/students",
      "/teachers",
      "/reports",
    ],
  },
};

export const ROLE_INFO = {
  SUPER_ADMIN: { file: "sa_frostfire.txt" },
  ADMIN: { file: "sa_flora.txt" },
  TEACHER: { file: "sa_SA-EMP-0001.txt" },
  STUDENT: { file: "sa_SA-ST-0001.txt" },
  STAFF: { file: "sa_DI-staff.txt" },
};